In [1]:
import pandas as pd

df = pd.read_csv('../01.Data_Collection/films.csv')

In [2]:
df.columns

Index(['F-rated', '감독', '감독_대표역할', '감독성별', '감독코드', '감독필모', '개봉일', '관객수', '국적',
       '누적관객수', '누적매출액', '대표감독', '대표국적', '대표작가', '대표작가(필명)', '등급', '매출액',
       '매출액점유율', '배급사', '배역명', '배우', '배우_대표역할', '배우성별', '배우코드', '배우필모', '상영횟수',
       '순위', '스크린수', '영화명', '영화코드', '작가', '작가_대표역할', '작가성별', '작가코드', '작가필모',
       '장르', '제작사', '주연배우'],
      dtype='object')

In [4]:
len(df.columns)

38

In [5]:
column_list = ['순위', '영화명', '영화코드', '개봉일', '매출액', '매출액점유율', '누적매출액', '관객수', '누적관객수', 
               '스크린수', '상영횟수', '대표국적', '국적', '제작사', '배급사', '등급', '장르', 'F-rated',
               '감독', '대표감독', '감독코드', '감독성별', '감독_대표역할', '감독필모',
               '작가', '대표작가', '대표작가(필명)', '작가코드', '작가성별', '작가_대표역할', '작가필모',  
               '배우', '주연배우', '배역명', '배우코드', '배우성별', '배우_대표역할', '배우필모']

df = df[column_list]

In [6]:
df.head()

,순위,영화명,영화코드,개봉일,매출액,매출액점유율,누적매출액,관객수,누적관객수,스크린수,...,작가성별,작가_대표역할,작가필모,배우,주연배우,배역명,배우코드,배우성별,배우_대표역할,배우필모
0,55.0,워킹걸,20147947,2015-01-07,1.183887e+09,0.1%,1.201963e+09,149181.0,151550.0,308.0,...,남자,감독,공포체험단 곤지암편|천문: 하늘에 묻는다|곤지암|워킹걸|미쓰GO|외톨이|기담|무서운...,"조여정,클라라,김태우,배유람,정범식,정범식,박주희,백경인,조은영,손진우,배성우,유찬...",조여정,NaN,10066680.0,여자,배우,기생충|워킹걸|인간중독|표적|후궁 : 제왕의 첩|방자전|흡혈형사 나도열
1,121.0,설해,20124398,2015-01-08,2.076750e+07,0.0%,2.977050e+07,2796.0,3933.0,34.0,...,남자,감독,설해|그 남자의 책 198쪽|바보|화성으로 간 사나이|동감|귀소,"박해진,이영아,송재희,전무송,최원주,이상민,이기열,윤기호,김수환,김정권,김혜진,박재...",박해진,상우,20126329.0,남자,배우,치즈인더트랩|설해|젓가락
2,26.0,허삼관,20131262,2015-01-14,7.408944e+09,0.8%,7.408944e+09,955679.0,955679.0,621.0,...,남자,배우,백두산|PMC: 더 벙커|클로젯|신과함께-인과 연|1987|신과함께-죄와 벌|서서평...,"하정우,하지원,전혜진,장광,주진모,성동일,이경영,김영애,정만식,조진웅,김기천,김성균...",하정우,허삼관,10087253.0,남자,배우,백두산|PMC: 더 벙커|클로젯|신과함께-인과 연|1987|신과함께-죄와 벌|서서평...
3,16.0,오늘의 연애,20142407,2015-01-14,1.492465e+10,1.7%,1.492465e+10,1891993.0,1891993.0,709.0,...,남자,감독,오늘의 연애|공범|내 사랑 내 곁에|그놈 목소리|너는 내 운명|죽어도 좋아|신비한 ...,"이승기,문채원,이서진,장진우,이경진,이동진,임하룡,이상협,김광규,김부선,가인,임종윤...",이승기,NaN,10056227.0,남자,배우,궁합|오늘의 연애
4,149.0,꽃보다 처녀귀신,20155744,2015-01-15,7.909000e+06,0.0%,7.909000e+06,1567.0,1567.0,5.0,...,남자,감독,꽃보다 처녀귀신|태양의 이면|바이칼|바르도|삼승할망|좀비처럼 걸어봐,"안재민,이정민,이정민,박승찬,이현복,최경택,손지훈,우경희,유재훈,이돌,하혜정,한상민...",안재민,NaN,20204727.0,남자,배우,꽃보다 처녀귀신

In [9]:
df.to_excel('../01.Data_Collection/films.xlsx', index=False)