In [1]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [2]:
# plot 한글출력
plt.rcParams['font.family'] = 'NanumGothic'

In [3]:
# warning message 제거
import warnings
warnings.filterwarnings('ignore')

# Data

## 영화정보 전체년도

In [6]:
audits_2015 = pd.read_csv('../Data/audits_2015_ko.csv')
show_time_2015 = pd.read_csv('../Data/showTm_2015_ko.csv')
companys_2015 = pd.read_csv('../Data/companys_2015_ko.csv')
boxoffice_2015 = pd.read_csv('../Data/KOBIS_boxoffice_2015_filtered.csv')

audits_2016 = pd.read_csv('../Data/audits_2016_ko.csv')
show_time_2016 = pd.read_csv('../Data/showTm_2016_ko.csv')
companys_2016 = pd.read_csv('../Data/companys_2016_ko.csv')
boxoffice_2016 = pd.read_csv('../Data/KOBIS_boxoffice_2016_filtered.csv')

audits_2017 = pd.read_csv('../Data/audits_2017_ko.csv')
show_time_2017 = pd.read_csv('../Data/showTm_2017_ko.csv')
companys_2017 = pd.read_csv('../Data/companys_2017_ko.csv')
boxoffice_2017 = pd.read_csv('../Data/KOBIS_boxoffice_2017_filtered.csv')

audits_2018 = pd.read_csv('../Data/audits_2018_ko.csv')
show_time_2018 = pd.read_csv('../Data/showTm_2018_ko.csv')
companys_2018 = pd.read_csv('../Data/companys_2018_ko.csv')
boxoffice_2018 = pd.read_csv('../Data/KOBIS_boxoffice_2018_filtered.csv')

audits_2019 = pd.read_csv('../Data/audits_2019_ko.csv')
show_time_2019 = pd.read_csv('../Data/showTm_2019_ko.csv')
companys_2019 = pd.read_csv('../Data/companys_2019_ko.csv')
boxoffice_2019 = pd.read_csv('../Data/KOBIS_boxoffice_2019_filtered.csv')

print('audits_2015', audits_2015.shape)
print('audits_2016', audits_2016.shape)
print('audits_2017', audits_2017.shape)
print('audits_2018', audits_2018.shape)
print('audits_2019', audits_2019.shape)

print('show_time_2015', show_time_2015.shape)
print('show_time_2016', show_time_2016.shape)
print('show_time_2017', show_time_2017.shape)
print('show_time_2018', show_time_2018.shape)
print('show_time_2019', show_time_2019.shape)

print('companys_2015', companys_2015.shape)
print('companys_2016', companys_2016.shape)
print('companys_2017', companys_2017.shape)
print('companys_2018', companys_2018.shape)
print('companys_2019', companys_2019.shape)

print('boxoffice_2015', companys_2015.shape)
print('boxoffice_2016', companys_2016.shape)
print('boxoffice_2017', companys_2017.shape)
print('boxoffice_2018', companys_2018.shape)
print('boxoffice_2019', companys_2019.shape)

audits_2015 (166, 3)
audits_2016 (166, 3)
audits_2017 (162, 3)
audits_2018 (173, 3)
audits_2019 (141, 3)
show_time_2015 (164, 2)
show_time_2016 (168, 2)
show_time_2017 (162, 2)
show_time_2018 (172, 2)
show_time_2019 (140, 2)
companys_2015 (694, 4)
companys_2016 (622, 4)
companys_2017 (619, 4)
companys_2018 (634, 4)
companys_2019 (511, 4)
boxoffice_2015 (694, 4)
boxoffice_2016 (622, 4)
boxoffice_2017 (619, 4)
boxoffice_2018 (634, 4)
boxoffice_2019 (511, 4)

In [65]:
audits = pd.concat([audits_2015, audits_2016, audits_2017, audits_2018, audits_2019])
show_time = pd.concat([show_time_2015, show_time_2016, show_time_2017, show_time_2018, show_time_2019])
companys = pd.concat([companys_2015, companys_2016, companys_2017, companys_2018, companys_2019])
boxoffice = pd.concat([boxoffice_2015, boxoffice_2016, boxoffice_2017, boxoffice_2018, boxoffice_2019])

In [67]:
print(audits.shape)
print(show_time.shape)
print(companys.shape)
print(boxoffice.shape)

(808, 3)
(806, 2)
(3080, 4)
(802, 18)

In [68]:
audits.to_csv('Data/audits.csv', index=False)
show_time.to_csv('Data/show_time.csv', index=False)
companys.to_csv('Data/companys.csv', index=False)
boxoffice.to_csv('Data/boxoffice.csv', index=False)

In [70]:
pd.read_csv('Data/audits.csv').sample()

           auditNo   movieCd watchGradeNm
381  2017-MF00741   20174644     12세이상관람가

## 배우 데이터 전체년도

In [8]:
actors_2015 = pd.read_csv('../Data/actors_2015_ko.csv')
actors_2016 = pd.read_csv('../Data/actors_2016_ko.csv')
actors_2017 = pd.read_csv('../Data/actors_2017_ko.csv')
actors_2018 = pd.read_csv('../Data/actors_2018_ko.csv')
actors_2019 = pd.read_csv('../Data/actors_2019_ko.csv')

actor_code_2015 = pd.read_csv('../Data/actorCd_2015_list.csv')
actor_code_2016 = pd.read_csv('../Data/actorCd_2016_list.csv')
actor_code_2017 = pd.read_csv('../Data/actorCd_2017_list.csv')
actor_code_2018 = pd.read_csv('../Data/actorCd_2018_list.csv')
actor_code_2019 = pd.read_csv('../Data/actorCd_2019_list.csv')

actor_detail_2015 = pd.read_csv('../Data/actor_detail_2015_ko.csv')
actor_detail_2016 = pd.read_csv('../Data/actor_detail_2016_ko.csv')
actor_detail_2017 = pd.read_csv('../Data/actor_detail_2017_ko.csv')
actor_detail_2018 = pd.read_csv('../Data/actor_detail_2018_ko.csv')
actor_detail_2019 = pd.read_csv('../Data/actor_detail_2019_ko.csv')

print('actors_2015', actors_2015.shape)
print('actors_2016', actors_2016.shape)
print('actors_2017', actors_2017.shape)
print('actors_2018', actors_2018.shape)
print('actors_2019', actors_2019.shape)

print('actor_code_2015', actor_code_2015.shape)
print('actor_code_2016', actor_code_2016.shape)
print('actor_code_2017', actor_code_2017.shape)
print('actor_code_2018', actor_code_2018.shape)
print('actor_code_2019', actor_code_2019.shape)

print('actor_detail_2015', actor_detail_2015.shape)
print('actor_detail_2015', actor_detail_2016.shape)
print('actor_detail_2015', actor_detail_2017.shape)
print('actor_detail_2015', actor_detail_2018.shape)
print('actor_detail_2015', actor_detail_2019.shape)

actors_2015 (2388, 5)
actors_2016 (1888, 5)
actors_2017 (2056, 5)
actors_2018 (3616, 5)
actors_2019 (1106, 5)
actor_code_2015 (2388, 5)
actor_code_2016 (1255, 5)
actor_code_2017 (2056, 5)
actor_code_2018 (3616, 5)
actor_code_2019 (1106, 5)
actor_detail_2015 (39862, 6)
actor_detail_2015 (21321, 6)
actor_detail_2015 (28960, 6)
actor_detail_2015 (36710, 6)
actor_detail_2015 (15575, 6)

In [9]:
actors = pd.concat([actors_2015, actors_2016, actors_2017, actors_2018, actors_2019])
actor_code = pd.concat([actor_code_2015, actor_code_2016, actor_code_2017, actor_code_2018, actor_code_2019])
actor_detail = pd.concat([actor_detail_2015, actor_detail_2016, actor_detail_2017, actor_detail_2018, actor_detail_2019])

actors.to_csv('../01.Data_Collection/actors.csv', index=False)
actor_code.to_csv('../01.Data_Collection/actor_code.csv', index=False)
actor_detail.to_csv('../01.Data_Collection/actor_detail.csv', index=False)

In [10]:
pd.read_csv('../01.Data_Collection/actors.csv')

                 cast   movieCd movieNm peopleNm repRoleNm
0                 서도철  20148048     베테랑      황정민        배우
1                 조태오  20148048     베테랑      유아인        배우
2                최 상무  20148048     베테랑      유해진        배우
3                오 팀장  20148048     베테랑      오달수        배우
4                 미스봉  20148048     베테랑      장윤주        배우
5                윤 형사  20148048     베테랑      김시후        배우
6                왕 형사  20148048     베테랑      오대환        배우
7                배 기사  20148048     베테랑      정웅인        배우
8                전 소장  20148048     베테랑      정만식        배우
9                 조회장  20148048     베테랑      송영창        배우
10                 주연  20148048     베테랑       진경        배우
11                 다혜  20148048     베테랑      유인영        배우
12              앳된 막내  20148048     베테랑      박소담        배우
13                윤홍렬  20148048     베테랑      이동휘        배우
14          중고차 매장 업주  20148048     베테랑      배성우        배우
15           광역수사대 총경  20148048     베테랑      천호진        배우
16              주연 동료  20148048     베테랑      이채은        배우
17               감찰반1  20148048     베테랑      조덕현        배우
18        윤홍렬소속여자연예인3  20148048     베테랑      신지수        배우
19           중고차 전문가3  20148048     베테랑      권지훈        배우
20            조선족 살수1  20148048     베테랑      정윤헌        배우
21           중고차 전문가1  20148048     베테랑      장한승        배우
22           중고차 전문가2  20148048     베테랑      김선웅        배우
23            중고차 문지기  20148048     베테랑      김성종        배우
24          신진물산 법무팀1  20148048     베테랑      우영택        배우
25            관할 담당경찰  20148048     베테랑      김민재        배우
26            배 기사 아들  20148048     베테랑      김재현        배우
27          신진물산 법무팀2  20148048     베테랑      김태용        배우
28            광수대 형사4  20148048     베테랑      김지수        배우
29          뉴스 기자 목소리  20148048     베테랑      박지윤        배우
...               ...       ...     ...      ...       ...
11024              문광  20183782     기생충      이정은        배우
11025              근세  20183782     기생충      박명훈        배우
11026              다혜  20183782     기생충      정지소        배우
11027              다송  20183782     기생충      정현준        배우
11028       JTBC 현장기자  20183782     기생충      윤혜리        배우
11029             윤기사  20183782     기생충      박근록        배우
11030             NaN  20184621     엑시트      조정석        배우
11031             NaN  20184621     엑시트       윤아        배우
11032             NaN  20184621     엑시트      고두심        배우
11033             NaN  20184621     엑시트      박인환        배우
11034             NaN  20184621     엑시트      김지영        배우
11035           구 점장   20184621     엑시트      강기영        배우
11036        드론 형제 형   20184621     엑시트      오희준        배우
11037             NaN  20184621     엑시트      배유람        배우
11038             용수   20184621     엑시트      유수빈        배우
11039            택시손님  20184621     엑시트      조성희        배우
11040  돌잔치 엄마/ 미희 목소리  20184621     엑시트      주보비        배우
11041             고반장  20182530    극한직업      류승룡        배우
11042             장형사  20182530    극한직업      이하늬        배우
11043             마형사  20182530    극한직업      진선규        배우
11044              영호  20182530    극한직업      이동휘        배우
11045              재훈  20182530    극한직업       공명        배우
11046            홍상필   20182530    극한직업      양현민        배우
11047              선희  20182530    극한직업      장진희        배우
11048             정실장  20182530    극한직업      허준석        배우
11049        마포서 강력반1  20182530    극한직업      한준우        배우
11050       정실장 넥타이직원  20182530    극한직업      김명준        배우
11051      안산분점 조직원 2  20182530    극한직업       나철        배우
11052        궁평항 제복경찰  20182530    극한직업      정재광        배우
11053         부산분점 손님  20182530    극한직업      정원창        배우

[11054 rows x 5 columns]

## 감독 데이터 전체년도

In [15]:
directors_2015 = pd.read_csv('../Data/directors_2015_ko.csv')
directors_2016 = pd.read_csv('../Data/directors_2016_ko.csv')
directors_2017 = pd.read_csv('../Data/directors_2017_ko.csv')
directors_2018 = pd.read_csv('../Data/directors_2018_ko.csv')
directors_2019 = pd.read_csv('../Data/directors_2019_ko.csv')

director_code_2015 = pd.read_csv('../Data/directorCd_2015_list.csv')
director_code_2016 = pd.read_csv('../Data/directorCd_2016_list.csv')
director_code_2017 = pd.read_csv('../Data/directorCd_2017_list.csv')
director_code_2018 = pd.read_csv('../Data/directorCd_2018_list.csv')
director_code_2019 = pd.read_csv('../Data/directorCd_2019_list.csv')

director_detail_2015 = pd.read_csv('../Data/director_detail_2015_ko.csv')
director_detail_2016 = pd.read_csv('../Data/director_detail_2016_ko.csv')
director_detail_2017 = pd.read_csv('../Data/director_detail_2017_ko.csv')
director_detail_2018 = pd.read_csv('../Data/director_detail_2018_ko.csv')
director_detail_2019 = pd.read_csv('../Data/director_detail_2019_ko.csv')

print('directors_2015', directors_2015.shape)
print('directors_2016', directors_2016.shape)
print('directors_2017', directors_2017.shape)
print('directors_2018', directors_2018.shape)
print('directors_2019', directors_2019.shape)

print('director_code_2015', director_code_2015.shape)
print('director_code_2016', director_code_2016.shape)
print('director_code_2017', director_code_2017.shape)
print('director_code_2018', director_code_2018.shape)
print('director_code_2019', director_code_2019.shape)

print('director_detail_2015', director_detail_2015.shape)
print('director_detail_2016', director_detail_2016.shape)
print('director_detail_2017', director_detail_2017.shape)
print('director_detail_2018', director_detail_2018.shape)
print('director_detail_2019', director_detail_2019.shape)

directors_2015 (178, 4)
directors_2016 (181, 4)
directors_2017 (185, 4)
directors_2018 (187, 4)
directors_2019 (158, 4)
director_code_2015 (178, 5)
director_code_2016 (181, 5)
director_code_2017 (185, 5)
director_code_2018 (187, 5)
director_code_2019 (158, 5)
director_detail_2015 (3004, 6)
director_detail_2016 (3087, 6)
director_detail_2017 (2418, 6)
director_detail_2018 (2710, 6)
director_detail_2019 (1864, 6)

In [16]:
directors = pd.concat([directors_2015, directors_2016, directors_2017, directors_2018, directors_2019])
director_code = pd.concat([director_code_2015, director_code_2016, director_code_2017, director_code_2018, director_code_2019])
director_detail = pd.concat([director_detail_2015, director_detail_2016, director_detail_2017, director_detail_2018, director_detail_2019])

directors.to_csv('../01.Data_Collection/directors.csv', index=False)
director_code.to_csv('../01.Data_Collection/director_code.csv', index=False)
director_detail.to_csv('../01.Data_Collection/director_detail.csv', index=False)

In [17]:
pd.read_csv('../01.Data_Collection/directors.csv')

      movieCd           movieNm peopleNm repRoleNm
0    20148048               베테랑      류승완        감독
1    20148851                암살      최동훈        감독
2    20149314              내부자들      우민호        감독
3    20145503            검은 사제들      장재현        감독
4    20148846                사도      이준익        감독
5    20134798              연평해전      김학순        감독
6    20148845                스물      이병헌        감독
7    20136068              히말라야      이석훈        감독
8    20149570  조선명탐정 : 사라진 놉의 딸      김석윤        감독
9    20148855              극비수사      곽경택        감독
10   20149569            악의 연대기      백운학        감독
11   20156557        탐정 : 더 비기닝      김정훈        감독
12   20157464               더 폰      김봉주        감독
13   20136888           강남 1970       유하        감독
14   20140703              장수상회      강제규        감독
15   20143572           뷰티 인사이드        백        감독
16   20148188               쎄시봉      김현석        감독
17   20142407            오늘의 연애      박진표        감독
18   20149266             차이나타운      한준희        감독
19   20142402                간신      민규동        감독
20   20145171                대호      박훈정        감독
21   20157465              그놈이다      윤준형        감독
22   20142855            성난 변호사      허종호        감독
23   20148461              살인의뢰      손용호        감독
24   20145504         특종: 량첸살인기       노덕        감독
25   20156748        열정같은소리하고있네      정기훈        감독
26   20143513            미쓰 와이프      강효진        감독
27   20131262               허삼관      하정우        감독
28   20148841               헬머니      신한솔        감독
29   20130566               무뢰한      오승욱        감독
..        ...               ...      ...       ...
859  20194456             양자물리학      이성태        감독
860  20180825               미성년      김윤석        감독
861  20185985        광대들: 풍문조작단      김주호        감독
862  20198453   롱 리브 더 킹: 목포 영웅      강윤성        감독
863  20182490             나랏말싸미      조철현        감독
864  20187322      힘을 내요, 미스터 리      이계벽        감독
865  20196601        항거:유관순 이야기      조민호        감독
866  20180868                뺑반      한준희        감독
867  20193601     장사리 : 잊혀진 영웅들      김태훈        감독
868  20193601     장사리 : 잊혀진 영웅들      곽경택        감독
869  20180442                사자      김주환        감독
870  20184483              퍼펙트맨       용수        감독
871  20185784         나의 특별한 형제      육상효        감독
872  20181416          유열의 음악앨범      정지우        감독
873  20176251            내안의 그놈      강효진        감독
874  20184082               걸캅스      정다원        감독
875  20184543                변신      김홍선        감독
876  20184572       타짜: 원 아이드 잭      권오광        감독
877  20183096                생일      이종언        감독
878  20177539               사바하      장재현        감독
879  20184105               말모이      엄유나        감독
880  20185881                증인       이한        감독
881  20195920         가장 보통의 연애      김한결        감독
882  20188941               악인전      이원태        감독
883  20184462            봉오동 전투      원신연        감독
884  20188750      나쁜 녀석들: 더 무비      손용호        감독
885  20176103                 돈      박누리        감독
886  20183782               기생충      봉준호        감독
887  20184621               엑시트      이상근        감독
888  20182530              극한직업      이병헌        감독

[889 rows x 4 columns]

## 작가 데이터 전체년도

In [23]:
staffs_2015 = pd.read_csv('../Data/staffs_2015_ko.csv')
staffs_2016 = pd.read_csv('../Data/staffs_2016_ko.csv')
staffs_2017 = pd.read_csv('../Data/staffs_2017_ko.csv')
staffs_2018 = pd.read_csv('../Data/staffs_2018_ko.csv')
staffs_2019 = pd.read_csv('../Data/staffs_2019_ko.csv')

writer_code_2015 = pd.read_csv('../Data/writerCd_2015_list.csv')
writer_code_2016 = pd.read_csv('../Data/writerCd_2016_list.csv')
writer_code_2017 = pd.read_csv('../Data/writerCd_2017_list.csv')
writer_code_2018 = pd.read_csv('../Data/writerCd_2018_list.csv')
writer_code_2019 = pd.read_csv('../Data/writerCd_2019_list.csv')

writer_detail_2015 = pd.read_csv('../Data/writer_detail_2015_ko.csv')
writer_detail_2016 = pd.read_csv('../Data/writer_detail_2016_ko.csv')
writer_detail_2017 = pd.read_csv('../Data/writer_detail_2017_ko.csv')
writer_detail_2018 = pd.read_csv('../Data/writer_detail_2018_ko.csv')
writer_detail_2019 = pd.read_csv('../Data/writer_detail_2019_ko.csv')

print('staffs_2015', staffs_2015.shape)
print('staffs_2016', staffs_2016.shape)
print('staffs_2017', staffs_2017.shape)
print('staffs_2018', staffs_2018.shape)
print('staffs_2019', staffs_2019.shape)

print('writer_code_2015', writer_code_2015.shape)
print('writer_code_2016', writer_code_2016.shape)
print('writer_code_2017', writer_code_2017.shape)
print('writer_code_2018', writer_code_2018.shape)
print('writer_code_2019', writer_code_2019.shape)

print('writer_detail_2015', writer_detail_2015.shape)
print('writer_detail_2016', writer_detail_2016.shape)
print('writer_detail_2017', writer_detail_2017.shape)
print('writer_detail_2018', writer_detail_2018.shape)
print('writer_detail_2019', writer_detail_2019.shape)

staffs_2015 (23444, 4)
staffs_2016 (23554, 4)
staffs_2017 (24979, 4)
staffs_2018 (29177, 4)
staffs_2019 (6114, 4)
writer_code_2015 (194, 5)
writer_code_2016 (200, 5)
writer_code_2017 (187, 5)
writer_code_2018 (253, 5)
writer_code_2019 (181, 5)
writer_detail_2015 (2499, 6)
writer_detail_2016 (2555, 6)
writer_detail_2017 (2217, 6)
writer_detail_2018 (2928, 6)
writer_detail_2019 (2016, 6)

In [24]:
staffs = pd.concat([staffs_2015, staffs_2016, staffs_2017, staffs_2018, staffs_2019])
writer_code = pd.concat([writer_code_2015, writer_code_2016, writer_code_2017, writer_code_2018, writer_code_2019])
writer_detail = pd.concat([writer_detail_2015, writer_detail_2016, writer_detail_2017, writer_detail_2018, writer_detail_2019])

staffs.to_csv('../01.Data_Collection/staffs.csv', index=False)
writer_code.to_csv('../01.Data_Collection/writer_code.csv', index=False)
writer_detail.to_csv('../01.Data_Collection/writer_detail.csv', index=False)

In [25]:
pd.read_csv('../01.Data_Collection/writer_detail.csv')

        movieCd              movieNm moviePartNm  peopleCd peopleNm sex
0      20184621                  엑시트          제작  10019069      류승완  남자
1      20177539                  사바하          제작  10019069      류승완  남자
2      20161481                  군함도          감독  10019069      류승완  남자
3      20161481                  군함도    시나리오(각본)  10019069      류승완  남자
4      20161481                  군함도          기획  10019069      류승완  남자
5      20177063              군함도 감독판          감독  10019069      류승완  남자
6      20148048                  베테랑          감독  10019069      류승완  남자
7      20148048                  베테랑    시나리오(각본)  10019069      류승완  남자
8      20124083                  베를린          감독  10019069      류승완  남자
9      20124083                  베를린    시나리오(각본)  10019069      류승완  남자
10     20124083                  베를린          기획  10019069      류승완  남자
11     20102415                  평양성          배우  10019069      류승완  남자
12     20100213                 부당거래          감독  10019069      류승완  남자
13     20100213                 부당거래          각색  10019069      류승완  남자
14     20100213                 부당거래          제작  10019069      류승완  남자
15     20100305                  해결사          제작  10019069      류승완  남자
16     20100305                  해결사    시나리오(각본)  10019069      류승완  남자
17     20080833                다찌마와리          감독  10019069      류승완  남자
18     20080833                다찌마와리          배우  10019069      류승완  남자
19     20080833                다찌마와리    시나리오(각본)  10019069      류승완  남자
20     20080912        감독들, 김기영을 말하다          배우  10019069      류승완  남자
21     20060134                   짝패          감독  10019069      류승완  남자
22     20060134                   짝패          배우  10019069      류승완  남자
23     20060134                   짝패    시나리오(각본)  10019069      류승완  남자
24     20060134                   짝패          제작  10019069      류승완  남자
25     20050049  주먹이 운다(Crying Fist)          감독  10019069      류승완  남자
26     20050049  주먹이 운다(Crying Fist)    시나리오(각본)  10019069      류승완  남자
27     20040488            아라한 장풍대작전          감독  10019069      류승완  남자
28     20040488            아라한 장풍대작전    시나리오(각본)  10019069      류승완  남자
29     20020226                 오아시스          배우  10019069      류승완  남자
...         ...                  ...         ...       ...      ...  ..
12185  19990069                   유령    시나리오(각본)  10031641      봉준호  남자
12186  19970020               모텔 선인장    시나리오(각본)  10031641      봉준호  남자
12187  20072091                인플루엔자          감독  10031641      봉준호  남자
12188  20038957             싱크 & 라이즈          감독  10031641      봉준호  남자
12189  20149067                  백색인          감독  10031641      봉준호  남자
12190  20100457                 지리멸렬          감독  10031641      봉준호  남자
12191  20126732           프레임 속의 기억들          감독  10031641      봉준호  남자
12192  20149138         인디포럼2014 필름1          감독  10031641      봉준호  남자
12193  20081420                  도쿄!          감독  10031641      봉준호  남자
12194  20081420                  도쿄!    시나리오(각본)  10031641      봉준호  남자
12195  20183782                  기생충    시나리오(각본)  20200455      한진원  남자
12196  20144641                  판도라         연출팀  20200455      한진원  남자
12197  20143512            위험한 상견례 2         연출팀  20200455      한진원  남자
12198  20148841                  헬머니          배우  20200455      한진원  남자
12199  20148841                  헬머니         연출팀  20200455      한진원  남자
12200  20149514                  다우더         연출팀  20200455      한진원  남자
12201  20136312           아빠를 빌려드립니다         연출팀  20200455      한진원  남자
12202  20184621                  엑시트          감독  20111926      이상근  남자
12203  20184621                  엑시트    시나리오(각본)  20111926      이상근  남자
12204  20100671           간만에 나온 종각이          감독  20111926      이상근  남자
12205  20080444               명환이 셀카          감독  20111926      이상근  남자
12206  20080444               명환이 셀카    시나리오(각본)  20111926      이상근  남자
12207  20110104           베이베를 원하세요?          감독  20111926      이상근  남자
12208  20060625         감상과 이해, 청산별곡          감독  20111926      이상근  남자
12209  20060625         감상과 이해, 청산별곡          편집  20111926      이상근  남자
12210  20060625         감상과 이해, 청산별곡    시나리오(각본)  20111926      이상근  남자
12211  20048054                 견제부자          조명  20111926      이상근  남자
12212  20048054                 견제부자          촬영  20111926      이상근  남자
12213  20110823   제10회 미쟝센 단편영화제-개막식          감독  20111926      이상근  남자
12214  20182530                 극한직업    시나리오(각본)  20303529      문충일  남자

[12215 rows x 6 columns]

### 데이터 확인

In [6]:
audits.sample()

          auditNo   movieCd watchGradeNm
40  2015-MF00623   20136057     15세이상관람가

In [7]:
show_time.sample()

     movieCd  showTm
22  20142855     116

In [8]:
companys.sample()

     companyCd  companyNm companyPartNm   movieCd
328   20100410  오퍼스픽쳐스(유)           배급사  20157587

In [64]:
print(boxoffice_2015.isnull().sum())
boxoffice_2015.sample()

순위        0
영화명       0
개봉일       0
매출액       0
매출액점유율    0
누적매출액     0
관객수       0
누적관객수     0
스크린수      0
상영횟수      0
대표국적      0
국적        0
제작사       0
배급사       0
등급        0
장르        0
감독        0
배우        8
dtype: int64

,순위,영화명,개봉일,매출액,매출액점유율,누적매출액,관객수,누적관객수,스크린수,상영횟수,대표국적,국적,제작사,배급사,등급,장르,감독,배우
32,57,화장,2015.4.9,"1,073,035,100",0.1%,"1,073,964,100","142,382","142,519",327,"13,811",한국,한국,(주)명필름,(주)리틀빅픽쳐스,청소년관람불가,드라마,임권택,"안성기,김규리,김호정,박혜미,윤종호,이소정,이은경,안석환,연우진,김병춘,주현"

#### 영화정보 데이터셋
movieCd 로 audits + show_time merge

companys 제작사, 배급사, 제공 등 컬럼으로 넣기

In [21]:
print(actors.isnull().sum())
actors.sample()

cast         446
movieCd        0
movieNm        0
peopleNm       0
repRoleNm      0
dtype: int64

     cast   movieCd                  movieNm peopleNm repRoleNm
1440  NaN  20156441  최강전사 미니특공대 : 새로운 악당의 습격      엄상현        배우

→ cast 컬럼 = 배역 이름

cast 컬럼 Null 값은 엑스트라?

In [24]:
print(actor_code.isnull().sum())
actor_code.sample()
actor_code[actor_code['repRoleNm'].isnull()]

filmoNames    0
movieNm       0
peopleCd      0
peopleNm      0
repRoleNm     2
dtype: int64

,filmoNames,movieNm,peopleCd,peopleNm,repRoleNm
1322,다이노 타임|빌리와 용감한 녀석들 2 |주먹왕 랄프|바보 삼총사,다이노 타임,10063852,제인 린치,NaN
1631,기적의 피아노,기적의 피아노,20214267,박정순,NaN

→ repRoleNm Null 값
- 해당영화 역할
- peopleCd 로 검색

In [31]:
print(actor_detail.isnull().sum())
actor_detail[actor_detail['sex'].isnull()]
# actor_detail[actor_detail['peopleNm'] == '최화정']

movieCd         0
movieNm         0
moviePartNm     0
peopleCd        0
peopleNm        0
sex            39
dtype: int64

        movieCd            movieNm moviePartNm  peopleCd peopleNm  sex
2650   20149314               내부자들          배우  20185511      설우신  NaN
2651   20123383      화이: 괴물을 삼킨 아이          배우  20185511      설우신  NaN
2652   20126091                 관상     액션/스턴트팀  20185511      설우신  NaN
10323  20143572            뷰티 인사이드          배우  10089433      홍다미  NaN
10324  20060499                유리알          배우  10089433      홍다미  NaN
10325  20197748      동명이인 프로젝트 시즌3          배우  10089433      홍다미  NaN
27104  20100211             다이노 타임          배우  10063852    제인 린치  NaN
27105  20133924     빌리와 용감한 녀석들 2           배우  10063852    제인 린치  NaN
27106  20129388             주먹왕 랄프          배우  10063852    제인 린치  NaN
27107  20135112             바보 삼총사          배우  10063852    제인 린치  NaN
28625  20151782        지금은맞고그때는틀리다          배우  10072915      최화정  NaN
28626  20120106      뒷담화: 감독이 미쳤어요          배우  10072915      최화정  NaN
28627  19860074          몸 전체로 사랑을          배우  10072915      최화정  NaN
36458  20163218          위선자들: 감독판          배우  10060130      장두이  NaN
36459  20157191               위선자들          배우  10060130      장두이  NaN
36460  20136892                 청야          배우  10060130      장두이  NaN
36461  19940007               마스카라          배우  10060130      장두이  NaN
36462  19860014                 깜보          배우  10060130      장두이  NaN
36463  19778174  어디서 무엇이 되어 다시 만나리          배우  10060130      장두이  NaN
36869  20191845             난폭한 기록          배우  10062116      정의갑  NaN
36870  20149259                막걸스          배우  10062116      정의갑  NaN
36871  20137546                 만찬          배우  10062116      정의갑  NaN
36872  20070487        이브의 유혹 - 엔젤          배우  10062116      정의갑  NaN
36873  20111916                  원          배우  10062116      정의갑  NaN
37451  20141611                 들꽃          배우  10072468      최영록  NaN
37582  20136043           신이 보낸 사람          배우  10043336      안병경  NaN
37583  20136043           신이 보낸 사람          배우  10043336      안병경  NaN
37584  20133667              폴라로이드          배우  10043336      안병경  NaN
37585  19890073              단단한 놈          배우  10043336      안병경  NaN
37586  19840068           각설이 품바타령          배우  10043336      안병경  NaN
37587  19820034         복수는 내게 맡겨라          배우  10043336      안병경  NaN
37724  20133667              폴라로이드          배우  20230285      황서인  NaN
37725  20133667              폴라로이드          배우  20230285      황서인  NaN
37726  20133667              폴라로이드         조명팀  20230285      황서인  NaN
37727  20133667              폴라로이드          배우  20230285      황서인  NaN
37728  20133667              폴라로이드          배우  20230285      황서인  NaN
37729  20133667              폴라로이드         조명팀  20230285      황서인  NaN
37881  20143726           명령불복종 교사          배우  10072903      최혜원  NaN
37882  20143726           명령불복종 교사          촬영  10072903      최혜원  NaN

→ sex Null 값 
- 개별 서칭
- 다른 row 찾기

#### 배우 관련 데이터셋
[movieNm, peopleNm] 로 actors + actor_code merge

peopleCd 로 actor_code + actor_detail merge (peopleNm 중복)

In [32]:
print(directors.isnull().sum())
directors.sample()

movieCd      0
movieNm      0
peopleNm     0
repRoleNm    0
dtype: int64

      movieCd    movieNm peopleNm repRoleNm
176  20147929  메이드 인 차이나      김동후        감독

In [33]:
print(director_code.isnull().sum())
director_code.sample()

filmoNames    0
movieNm       0
peopleCd      0
peopleNm      0
repRoleNm     0
dtype: int64

,filmoNames,movieNm,peopleCd,peopleNm,repRoleNm
84,오! 문희|명량: 회오리 바다를 향하여|퍼펙트 게임|최종병기 활|인플루언스|애자|아...,명량: 회오리 바다를 향하여,20158266,정세교,감독

In [36]:
print(director_detail.isnull().sum())
director_detail[director_detail['sex'].isnull()]

movieCd         0
movieNm         0
moviePartNm     0
peopleCd        0
peopleNm        0
sex            16
dtype: int64

       movieCd            movieNm moviePartNm  peopleCd peopleNm  sex
1206  20141598                타이밍          감독  10028546      박대열  NaN
1207  20141598                타이밍      애니메이션팀  10028546      박대열  NaN
1208  20141598                타이밍       스토리보드  10028546      박대열  NaN
1209  20060378           애니 프란체스카          감독  10028546      박대열  NaN
1411  20189746  극장판 뽀잉: 슈퍼 변신의 비밀          기획  20214806       허선  NaN
1412  20189746  극장판 뽀잉: 슈퍼 변신의 비밀          제작  20214806       허선  NaN
1413  20154323           슈퍼레이서 엔지          감독  20214806       허선  NaN
1414  20154323           슈퍼레이서 엔지          기획  20214806       허선  NaN
1415  20154323           슈퍼레이서 엔지    시나리오(각본)  20214806       허선  NaN
1416  20154323           슈퍼레이서 엔지        프로듀서  20214806       허선  NaN
2628  20166441                 외도    시나리오(각본)  20216886     최율권희  NaN
2629  20161324        위험한 중독 무삭제판          감독  20216886     최율권희  NaN
2630  20150666             위험한 중독          감독  20216886     최율권희  NaN
2631  20150666             위험한 중독          각색  20216886     최율권희  NaN
2632  20158463          포장마차-무삭제판          감독  20216886     최율권희  NaN
2633  20155845               포장마차          감독  20216886     최율권희  NaN

→ sex Null 값
- 개별 서칭

#### 감독 관련 데이터셋
배우 데이터셋과 마찬가지로 merge

In [37]:
print(staffs.isnull().sum())
staffs.sample()

movieCd        0
movieNm        0
peopleNm       0
staffRoleNm    0
dtype: int64

      movieCd movieNm peopleNm staffRoleNm
819  20148851      암살      손병수    VFX 아티스트

In [41]:
print(writer_code.isnull().sum())
writer_code[writer_code['repRoleNm'].isnull()]

filmoNames    0
movieNm       0
peopleCd      0
peopleNm      0
repRoleNm     1
dtype: int64

   filmoNames movieNm  peopleCd peopleNm repRoleNm
82     다이노 타임  다이노 타임  10045509    애덤 비첸       NaN

→ repRoleNm Null 값
- 해당영화 역할
- peopleCd 로 검색

In [40]:
print(writer_detail.isnull().sum())
writer_detail[writer_detail['sex'].isnull()]

movieCd         0
movieNm         0
moviePartNm     0
peopleCd        0
peopleNm        0
sex            26
dtype: int64

       movieCd             movieNm moviePartNm  peopleCd peopleNm  sex
814   20156807  뽀로로 극장판 컴퓨터 왕국 대모험    시나리오(각본)  10057072      이인균  NaN
815   20123681    뽀로로 극장판 슈퍼썰매 대모험    시나리오(각본)  10057072      이인균  NaN
904   20100211              다이노 타임    시나리오(각본)  10045509    애덤 비첸  NaN
1033  20144442               조선마술사    시나리오(각본)  10066948      조정화  NaN
1034  20144442               조선마술사    시나리오(각본)  10066948      조정화  NaN
1035  20133811             슬기로운 해법    시나리오(각본)  10066948      조정화  NaN
1036  20030063          화성으로 간 사나이    시나리오(각본)  10066948      조정화  NaN
1037  20120745              해피버스데이         스토리  10066948      조정화  NaN
1038  20120741                교회누나    시나리오(각본)  10066948      조정화  NaN
1039  20020052             묻지마 패밀리    시나리오(각본)  10066948      조정화  NaN
1040  20144442               조선마술사    시나리오(각본)  10066948      조정화  NaN
1041  20144442               조선마술사    시나리오(각본)  10066948      조정화  NaN
1042  20133811             슬기로운 해법    시나리오(각본)  10066948      조정화  NaN
1043  20030063          화성으로 간 사나이    시나리오(각본)  10066948      조정화  NaN
1044  20120745              해피버스데이         스토리  10066948      조정화  NaN
1045  20120741                교회누나    시나리오(각본)  10066948      조정화  NaN
1046  20020052             묻지마 패밀리    시나리오(각본)  10066948      조정화  NaN
1272  20189746   극장판 뽀잉: 슈퍼 변신의 비밀          기획  20214806       허선  NaN
1273  20189746   극장판 뽀잉: 슈퍼 변신의 비밀          제작  20214806       허선  NaN
1274  20154323            슈퍼레이서 엔지          감독  20214806       허선  NaN
1275  20154323            슈퍼레이서 엔지          기획  20214806       허선  NaN
1276  20154323            슈퍼레이서 엔지    시나리오(각본)  20214806       허선  NaN
1277  20154323            슈퍼레이서 엔지        프로듀서  20214806       허선  NaN
1952  20133667               폴라로이드    시나리오(각본)  20229799       니쥔  NaN
2125  20158385               착한 처제    시나리오(각본)  20227240      여필주  NaN
2209  20153313            이바라키의 여름    시나리오(각본)  20229601      권초원  NaN

#### 작가 관련 데이터셋
배우, 감독 데이터셋과 마찬가지로 merge

## Merge

In [44]:
print(audits.shape, show_time.shape, companys.shape)

(166, 3) (164, 2) (694, 4)

In [48]:
audits.sample()

           auditNo   movieCd watchGradeNm
163  2014-MF01317   20155744      청소년관람불가

In [59]:
data = audits.merge(show_time, how='left', on='movieCd')
# companys 컬럼으로 넣기
data.isnull().sum()

companys.sample()
companys['companyPartNm'].value_counts()
# 제작사가 2개면 어떻게 넣을지

제작사                213
배급사                181
제공                 128
해외세일즈사             110
공동제공                48
제작서비스-후반작업(VFX)      6
제작서비스-시각효과/특수효과      5
제작서비스-분장/헤어          1
홍보사                  1
수입사                  1
Name: companyPartNm, dtype: int64