In [1]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [2]:
# plot 한글출력
plt.rcParams['font.family'] = 'NanumGothic'

In [3]:
# warning message 제거
import warnings
warnings.filterwarnings('ignore')

In [4]:
staffs = pd.read_csv('../01.Data_Collection/staffs.csv')
writer_code = pd.read_csv('../01.Data_Collection/writer_code.csv')
writer_detail = pd.read_csv('../01.Data_Collection/writer_detail.csv')
boxoffice = pd.read_csv('../01.Data_Collection/boxoffice.csv')

print(staffs.shape)
print(writer_code.shape)
print(writer_detail.shape)
print(boxoffice.shape)

(107268, 4)
(1015, 5)
(12215, 6)
(802, 18)

In [5]:
print(staffs.isnull().sum())
staffs[staffs['peopleNm'] == '애덤 비첸']

movieCd        0
movieNm        0
peopleNm       0
staffRoleNm    0
dtype: int64

        movieCd movieNm peopleNm staffRoleNm
15314  20100211  다이노 타임    애덤 비첸    시나리오(각본)

In [6]:
print(writer_code.isnull().sum())
writer_code[writer_code['repRoleNm'].isnull()]
# writer_code[writer_code['peopleNm'] == '애덤 비첸']
# writer_code['repRoleNm'].value_counts()

filmoNames    0
movieNm       0
peopleCd      0
peopleNm      0
repRoleNm     1
dtype: int64

   filmoNames movieNm  peopleCd peopleNm repRoleNm
82     다이노 타임  다이노 타임  10045509    애덤 비첸       NaN

In [7]:
# 애덤 비첸 repRoleNm 채우기

writer_code.loc[writer_code['peopleNm'] == '애덤 비첸', 'repRoleNm'] = '시나리오(각본)'

writer_code.isnull().sum()

filmoNames    0
movieNm       0
peopleCd      0
peopleNm      0
repRoleNm     0
dtype: int64

# staffs - writer_code merge
movieNm peopleNm 으로 merge

In [41]:
# staffs 테이블에서 각본가만 따로 저장
staff_writer_only = staffs[staffs['staffRoleNm'] == '시나리오(각본)']

print(staff_writer_only.shape)
staff_writer_only.sample()

(1015, 4)

       movieCd     movieNm peopleNm staffRoleNm
3969  20156557  탐정 : 더 비기닝      황혜순    시나리오(각본)

In [50]:
writer_code.shape
writer_code[writer_code.duplicated()]

,filmoNames,movieNm,peopleCd,peopleNm,repRoleNm
51,0.0MHz|내 심장을 쏴라|고死 두 번째 이야기: 교생실습|미스터 주부퀴즈왕|아라...,내 심장을 쏴라,10053709,유선동,감독
81,극장판 뽀잉: 슈퍼 변신의 비밀|슈퍼레이서 엔지|다이노 타임,다이노 타임,20229507,박재우,시나리오(각본)
92,조선마술사|슬기로운 해법|화성으로 간 사나이|해피버스데이|교회누나|묻지마 패밀리,조선마술사,10066948,조정화,시나리오(각본)
259,극장판 꼬마버스 타요의 에이스 구출작전,극장판 꼬마버스 타요의 에이스 구출작전,20254330,공병필,시나리오(각본)
296,미니특공대X|파워배틀 와치카: 와치가면의 역습|레이디버그|부릉! 부릉! 브루미즈: ...,파워배틀 와치카 미니카 배틀리그: 불꽃의 질주,10004783,김수훈,프로듀서
507,배심원들|메기|군산: 거위를 노래하다|리틀 포레스트|1987|여배우는 오늘도|특별시...,여배우는 오늘도,10026732,문소리,배우
508,배심원들|메기|군산: 거위를 노래하다|리틀 포레스트|1987|여배우는 오늘도|특별시...,여배우는 오늘도,10026732,문소리,배우
510,"에움길|소리꾼|귀향, 끝나지 않은 이야기|귀향|파울볼|두레소리","귀향, 끝나지 않은 이야기",10066934,조정래,감독
608,조선명탐정: 흡혈괴마의 비밀|우는 남자|캠퍼스 S 커플|추격자,조선명탐정: 흡혈괴마의 비밀,20135974,조은이,시나리오(각본)
616,재혼의 기술|발광하는 현대사|늦여름|딥|각자의 미식|게스트하우스|실종2|어떻게 헤어...,게스트하우스,10065915,조성규,감독
654,스텔라|인생은 아름다워(가제)|완벽한 타인|원더풀 고스트|7년의 밤|바람 바람 바람...,바람 바람 바람,10030154,배세영,시나리오(각본)
689,5.18 힌츠페터 스토리,5.18 힌츠페터 스토리,20319831,김소연,시나리오(각본)
691,버닝,버닝,20315560,오정미,시나리오(각본)
712,"허스토리|당신, 거기 있어줄래요|간신|내 아내의 모든 것|세상에서 가장 아름다운 이...",허스토리,10027774,민규동,감독
719,하트|밤치기|비치온더비치|조인성을 좋아하세요|극장에서 한 생각.|간밤에 꾼 꿈|처음...,너와 극장에서,20237286,정가영,감독
731,"인랑|밀정|라스트 스탠드|악마를 보았다|악마를 보았다 감독판|좋은 놈, 나쁜 놈, ...",인랑,10005852,김지운,감독
734,극장판 헬로카봇 : 달나라를 구해줘!|극장판 헬로카봇: 옴파로스 섬의 비밀|극장판 ...,극장판 헬로카봇 : 백악기 시대,20306429,조정희,시나리오(각본)
763,봄이가도,봄이가도,20322730,전신환,기획
797,해피 투게더|덫: 치명적인 유혹|남자 태어나다,해피 투게더,10057674,이창열,시나리오(각본)
819,다영씨|튼튼이의 모험,다영씨,20322632,임혜인,연출팀
828,"남산의 부장들|상류사회|인랑|천문: 하늘에 묻는다|마약왕|밀정|덕혜옹주|로봇, 소리",마약왕,20211246,이지민,시나리오(각본)
834,시간의 종말|다방의 푸른 꿈|한국번안가요사|살인의 강|내 신발에게,시간의 종말,20167301,김대현,감독
835,시간의 종말|다방의 푸른 꿈|한국번안가요사|살인의 강|내 신발에게,다방의 푸른 꿈,20167301,김대현,감독
836,자매의 공동묘지|몽달|열대야|애정소년 잔혹사|스타박'스 다방|어느 여름날 밤에|더티...,스타박'스 다방,20111446,이상우,감독
837,영주|비밀은 없다|돼지 같은 여자|물 좀 주소|미쓰 홍당무|사라진 밤|울지 않는다,영주,10071129,차성덕,감독
838,늙은 자전거|연평해전|아이 러브 유|학교전설,늙은 자전거,10026867,문희융,각색
843,우리마을|근본주의자|고봉수 감독 단편선|갈까부다|다영씨|튼튼이의 모험|델타 보이즈|...,델타 보이즈,20210668,고봉수,감독
844,인어전설|눈꺼풀|하늘의 황금마차|지슬 - 끝나지 않은 세월2|뽕똘|이어도|어이그 저...,인어전설,10050307,오멸,감독
845,인어전설|숨|패밀리마트,인어전설,20112077,전병원,시나리오(각본)
846,공포체험단 곤지암편|천문: 하늘에 묻는다|곤지암|워킹걸|미쓰GO|외톨이|기담|무서운...,곤지암,10061758,정범식,감독
847,곤지암|더 폰|워킹걸|페스티발|채식주의자|기담,곤지암,20316327,박상민,조감독
848,아픈 만큼 사랑한다|폴란드로 간 아이들|열세살 수아|누구나 비밀은 있다|나는 나를 ...,폴란드로 간 아이들,10072962,추상미,배우
849,다영씨|튼튼이의 모험,다영씨,20322632,임혜인,연출팀
850,다영씨|튼튼이의 모험,다영씨,20322632,임혜인,연출팀
852,도어락,도어락,20294870,박정희,시나리오(각본)
853,도어락|타이밍|내 연애의 기억|어깨 너머의 연인|꽃미남 연쇄 테러 사건|서프라이즈|...,도어락,10054870,이권,감독
854,부산행|화이: 괴물을 삼킨 아이,부산행,20171160,박주석,시나리오(각본)
858,산상수훈,산상수훈,20281369,유영의,감독
859,공작|춘몽|검사외전|허삼관|군도: 민란의 시대|범죄와의 전쟁: 나쁜놈들 전성시대|비...,공작,10054495,윤종빈,감독
860,공작|살인의뢰|점쟁이들|아부의 왕|코리아|독|방 안의 코끼리,공작,10002406,권성휘,시나리오(각본)
867,킹메이커 : 선거판의 여우|더러운 돈에 손대지 마라|불한당: 나쁜 놈들의 세상,불한당: 나쁜 놈들의 세상,20293189,김민수,감독
868,킹메이커 : 선거판의 여우|불한당: 나쁜 놈들의 세상|나의 PS 파트너 |청춘그루브|리얼,불한당: 나쁜 놈들의 세상,10031356,변성현,감독
870,"안녕, 나의 소녀 시절이여|순례","안녕, 나의 소녀 시절이여",20311191,김한석,감독
871,버블 패밀리,버블 패밀리,20276651,마민지,감독
872,버블 패밀리,버블 패밀리,10073067,니나 이야스,편집
879,국가부도의 날,국가부도의 날,20288890,엄성민,시나리오(각본)
880,어른이 되면,어른이 되면,20304969,장혜영,감독
931,"남산의 부장들|상류사회|인랑|천문: 하늘에 묻는다|마약왕|밀정|덕혜옹주|로봇, 소리",마약왕,20211246,이지민,시나리오(각본)
932,남산의 부장들|마약왕|내부자들: 디 오리지널|내부자들|간첩|파괴된 사나이|누가 예수...,마약왕,20111283,우민호,감독
933,"남산의 부장들|상류사회|인랑|천문: 하늘에 묻는다|마약왕|밀정|덕혜옹주|로봇, 소리",마약왕,20211246,이지민,시나리오(각본)
940,점박이 한반도의 공룡2 : 새로운 낙원|점박이:한반도의 공룡3D,점박이 한반도의 공룡2 : 새로운 낙원,20312035,한상호,감독
941,"힘을 내요, 미스터 리|점박이 한반도의 공룡2 : 새로운 낙원|럭키|마돈나|마담 뺑...",점박이 한반도의 공룡2 : 새로운 낙원,20149156,장윤미,시나리오(각본)
955,스윙키즈|타짜-신의 손|써니 감독판|써니|과속스캔들,스윙키즈,10000946,강형철,감독
974,PMC: 더 벙커|더 테러 라이브|리튼|아나모픽,PMC: 더 벙커,10004291,김병우,감독

In [47]:
writer_movie_code_merge = staff_writer_only.merge(writer_code, how='inner', on=['movieNm', 'peopleNm'])
# writer_movie_code_merge = writer_movie_code_merge.drop_duplicates()

print(writer_movie_code_merge.shape)
print(writer_movie_code_merge.isnull().sum())
writer_movie_code_merge.sample()

(1137, 7)
movieCd        0
movieNm        0
peopleNm       0
staffRoleNm    0
filmoNames     0
peopleCd       0
repRoleNm      0
dtype: int64

,movieCd,movieNm,peopleNm,staffRoleNm,filmoNames,peopleCd,repRoleNm
484,20164844,불한당: 나쁜 놈들의 세상,변성현,시나리오(각본),킹메이커 : 선거판의 여우|불한당: 나쁜 놈들의 세상|나의 PS 파트너 |청춘그루브|리얼,10031356,감독

In [25]:
writer_code.sample()

         filmoNames         movieNm  peopleCd peopleNm repRoleNm
799  번 더 스테이지: 더 무비  번 더 스테이지: 더 무비  20321940      이수진  시나리오(각본)

In [26]:
writer_detail.sample()

        movieCd  movieNm moviePartNm  peopleCd peopleNm sex
10157  20100353  파괴된 사나이    시나리오(각본)  20111283      우민호  남자

1. writer_detail 에서 staffs 에 있는 movieCd 만 남긴다

In [34]:
# staffs 에서 중복없이 movieCd 가져오기

movieCd = pd.DataFrame(staffs['movieCd'].unique(), columns=['movieCd'])
movieCd.sample()

      movieCd
665  20186652

In [ ]:
movieCd

In [35]:
# 가져온 movieCd 와 writer_detail 을 inner join

movieCd.merge(writer_detail, how='inner', on='movieCd')

ValueError: You are trying to merge on int64 and object columns. If you wish to proceed you should use pd.concat

## writer_detail table

In [8]:
print(writer_detail.isnull().sum())
writer_detail.sample()
writer_detail[writer_detail['sex'].isnull()]['peopleCd'].unique()

writer_detail[writer_detail['sex'].isnull()]

writer_detail[writer_detail['sex'].isnull()][['peopleCd', 'peopleNm']].drop_duplicates()

movieCd          0
movieNm          0
moviePartNm      0
peopleCd         0
peopleNm         0
sex            225
dtype: int64

       peopleCd   peopleNm
814    10057072        이인균
904    10045509      애덤 비첸
1033   10066948        조정화
1272   20214806         허선
1952   20229799         니쥔
2125   20227240        여필주
2209   20229601        권초원
2859   20200534        조성희
2994   20215586        천진우
3048   20232049        하영준
3161   10065836        조민주
3508   20256140      DJUNA
3561   20126211     크리스 덴크
3722   20263435        홍서율
4530   20231386        박재영
5286   20296969        류보라
5560   20277450        김연호
5573   20276950         양희
5574   20276711        한지원
5641   20277610        김승원
5670   20278849        이용희
5701   20278929        은하수
5821   20278949        김자영
6680   10060656        장호준
6995   20283089        권순규
6996   20283090        김황성
7138   20284969        김창원
7443   20315179        심혜영
7549   10026597       무라야마
7808   20232289        안소울
...         ...        ...
9989   20322037        이유리
9990   20321940        이수진
9991   20321647        유영은
10028  20288890        엄성민
10048  20313013        도경민
10049  20313014        구원경
10050  20313012        박은설
10051  20313032        김지현
10052  20313015        정유리
10053  20294870        박정희
10097  20322632        임혜인
10175  10073067     니나 이야스
10333  20295629        임나경
10593  20331192        황준현
10927  20331279        고경이
11051  20328095        박근영
11295  20325497        조진광
11521  20328892        김근라
11567  20313092        박수진
11592  10090734  후쿠시마 나오히로
11593  20127609      사토 다이
11595  20329892    우에노 키미코
11604  20302929        김성기
11757  20317073    히라노 야스시
11771  20283350        정서인
11772  20317072        지한솔
11773  20317043        이충복
11896  20321139        류경선
11926  20324734        금정연
12118  20305909        문지원

[86 rows x 2 columns]

In [9]:
writer_detail[writer_detail['peopleCd'] == 10057072]

      movieCd             movieNm moviePartNm  peopleCd peopleNm  sex
814  20156807  뽀로로 극장판 컴퓨터 왕국 대모험    시나리오(각본)  10057072      이인균  NaN
815  20123681    뽀로로 극장판 슈퍼썰매 대모험    시나리오(각본)  10057072      이인균  NaN

In [10]:
writer_code_only = pd.DataFrame(writer_detail['peopleCd'].unique(), columns=['peopleCd'])

writer_code_sex = writer_code_only.merge(writer_detail[['peopleCd', 'peopleNm', 'sex']], how='left', on='peopleCd').drop_duplicates()
writer_code_sex.sample()

      peopleCd peopleNm sex
7237  10028435      박경태  남자

In [11]:
writer_code_sex.groupby(['sex'])['peopleNm'].count()

sex
남자    532
여자    205
Name: peopleNm, dtype: int64

각본 공동집필이 많다
- 작품별 한명씩 보고
- 작품별 두명씩 보고

In [12]:
boxoffice.sample()

,순위,영화명,개봉일,매출액,매출액점유율,누적매출액,관객수,누적관객수,스크린수,상영횟수,대표국적,국적,제작사,배급사,등급,장르,감독,배우
662,20,마약왕,2018.12.19,"15,784,724,552",1.7%,"15,784,724,552","1,813,594","1,813,594","1,297","41,658",한국,한국,(주)하이브미디어코프,(주)쇼박스,청소년관람불가,"범죄,드라마",우민호,"송강호,조정석,배두나,김소진,김대명,이희준,조우진,이성민,김홍파,김근영,강민석,강민..."

In [13]:
staffs.sample()

         movieCd  movieNm peopleNm staffRoleNm
104067  20177552  국가부도의 날      박준서        사운드팀

In [14]:
staffs[staffs['staffRoleNm'] == '시나리오(각본)'].groupby(['movieCd'])['peopleNm'].count()

# staffs[(staffs['staffRoleNm'] == '시나리오(각본)') & (staffs['movieCd'] == 20100211)]
staffs[(staffs['staffRoleNm'] == '시나리오(각본)') & (staffs['movieCd'] == 20120422)]

        movieCd movieNm peopleNm staffRoleNm
45679  20120422   거미의 땅      김동령    시나리오(각본)
45680  20120422   거미의 땅      박경태    시나리오(각본)

In [15]:
writer_detail[writer_detail['peopleNm'] == '김동령']
writer_detail[writer_detail['peopleNm'] == '박경태']

       movieCd      movieNm moviePartNm  peopleCd peopleNm sex
4758  20190665  임신한 나무와 도깨비          감독  10028435      박경태  남자
4759  20120422        거미의 땅          감독  10028435      박경태  남자
4760  20120422        거미의 땅    시나리오(각본)  10028435      박경태  남자
4761  20120422        거미의 땅          편집  10028435      박경태  남자
4762  20120422        거미의 땅          촬영  10028435      박경태  남자
4763  20090349   사당동 더하기 22          감독  10028435      박경태  남자
4764  20090349   사당동 더하기 22          촬영  10028435      박경태  남자
4765  20060444       나와 부엉이          감독  10028435      박경태  남자

In [16]:
boxoffice[boxoffice['영화명'] == '거미의 땅']

,순위,영화명,개봉일,매출액,매출액점유율,누적매출액,관객수,누적관객수,스크린수,상영횟수,대표국적,국적,제작사,배급사,등급,장르,감독,배우
168,179,거미의 땅,2016.1.14,"6,489,100",0.0%,"7,667,100","1,025","1,291",6,113,한국,한국,(주)시네마달,(주)시네마달,15세이상관람가,다큐멘터리,"박경태,김동령",NaN

각본은 순서를 알 수 없음

감독이 각본을 쓴 경우에는 boxoffice 에서 확인가능

In [18]:
# 외국인

# writer_distinct = writer_detail[writer_detail['sex'].isnull()][['peopleCd', 'peopleNm']].drop_duplicates()

# writer_distinct['Korean'] = (len(writer_distinct['peopleNm']) == 3) # 왜 안됨???

# # len(writer_distinct['peopleNm'][814])
# writer_distinct