In [10]:
import os
import datetime
import pandas as pd

In [54]:
# 일별 좌석점유율 http://www.kobis.or.kr/kobis/business/stat/boxs/findDailySeatTicketList.do
    
NAME = 'findDailySeatTicketList'
URL = f'http://www.kobis.or.kr/kobis/business/stat/boxs/{NAME}.do'

date = datetime.date(2015, 1, 1)

while date < datetime.date(2015, 1, 15):
    start_date = date.isoformat()
    end_date = (date + datetime.timedelta(days=6)).isoformat()
    print(start_date, '~', end_date)
    os.system(f'curl "{URL}?loadEnd=0&dmlMode=excel&' \
              f'startDate={start_date}&endDate={end_date}&repNationCd=1&searchType=2"' \
              f' > 일별좌석점유율-{start_date}.html')
    date += datetime.timedelta(days=7)

2015-01-01 ~ 2015-01-07
2015-01-08 ~ 2015-01-14

In [57]:
df = pd.DataFrame()

date = datetime.date(2015, 1, 1)

while date < datetime.date(2015, 1, 15):
    start_date = date.isoformat()

    seat = pd.read_html(f'일별좌석점유율-{start_date}.html', encoding='utf-8')

    for i in range(1,8)[::-1]:
         df2 = seat[i][:-1]
         df = pd.concat([df, df2])
    date += datetime.timedelta(days=7)

In [58]:
df

,순위,영화명,개봉일,좌석판매율,좌석점유율,좌석수,매출액,누적매출액,관객수,누적관객수
0,1,국제시장,2014-12-17,78.0%,34.99%,964153,6129982500,47219550096,751754,6097431
1,2,기술자들,2014-12-24,57.9%,10.05%,276896,1299883700,14952363848,160371,1938454
2,3,"님아, 그 강을 건너지 마오",2014-11-27,67.2%,9.66%,266197,1479015600,31324845079,178941,4025319
3,4,개를 훔치는 완벽한 방법,2014-12-31,48.1%,2.85%,78410,299346400,608002300,37741,80633
4,5,상의원,2014-12-24,46.6%,2.22%,61095,230484800,5524209364,28439,705071
5,6,더 테너 리리코 스핀토,2014-12-31,18.9%,1.63%,44800,69620500,200984700,8446,26316
6,7,뽀로로 극장판 눈요정 마을 대모험,NaN,51.8%,0.39%,10741,27846600,1188395900,5561,237436
7,8,그 사람 그 사랑 그 세상,2014-11-20,45.9%,0.1%,2621,9467000,162552500,1202,22070
8,9,쿼바디스,2014-12-10,24.6%,0.08%,2073,4046900,117029800,509,15399
9,10,목숨,2014-12-04,9.8%,0.07%,1835,1399500,275635600,179,35844
10,11,장군의 아들,1990-06-09,18.4%,0.04%,1132,416000,1446000,208,723
11,12,"제자, 옥한흠",2014-10-30,15.9%,0.02%,548,687000,356418200,87,48547
12,12,다이빙벨,2014-10-23,18.2%,0.02%,435,627000,336231500,79,48571
13,14,카트,2014-11-13,62.7%,0.01%,316,1720800,5914397433,198,812688
14,14,파티51,2014-12-11,8.5%,0.01%,398,225000,13434800,34,1804
15,14,거인,2014-11-13,9.4%,0.01%,244,156000,175489400,23,23176
16,14,민우씨 오는 날,NaN,4.6%,0.01%,373,87000,3415500,17,695
17,14,GROW: 인피니트의 리얼 청춘 라이프,2014-12-04,5.2%,0.01%,173,54000,189463200,9,23874
18,14,두 번째 엄마,2014-12-31,2.0%,0.01%,205,32000,552000,4,153
19,14,카토 프로젝트,2014-04-17,0.3%,0.01%,300,2000,1886000,1,619
20,14,빅매치,2014-11-27,0.0%,0.01%,357,0,8952096578,0,1177438
21,22,한여름의 판타지아,2015-06-11,62.3%,0%,77,374600,996100,48,148
22,22,자유의 언덕,2014-09-04,30.3%,0%,76,207000,309165827,23,38101
23,22,앙상블,2014-12-18,17.0%,0%,94,140000,6045500,16,778
24,22,숫호구,2014-08-07,2.0%,0%,102,14000,16270000,2,2105
25,22,명기,2014-12-30,1.3%,0%,76,9000,647000,1,242
0,1,국제시장,2014-12-17,49.8%,34.95%,946099,3782877729,51002427825,470690,6568121
1,2,기술자들,2014-12-24,34.7%,10.12%,273941,758620771,15710984619,95119,2033573
2,3,"님아, 그 강을 건너지 마오",2014-11-27,39.2%,9.47%,256411,809774300,32134619379,100585,4125904
3,4,개를 훔치는 완벽한 방법,2014-12-31,29.8%,2.86%,77386,177849329,785851629,23074,103707
...,...,...,...,...,...,...,...,...,...,...
1,2,오늘의 연애,2015-01-14,26.4%,20.09%,507648,1032903000,1099473000,133838,141522
2,3,허삼관,2015-01-14,15.2%,19.22%,485583,551479100,615567100,73635,81503
3,4,"님아, 그 강을 건너지 마오",2014-11-27,16.2%,2.22%,56201,64991300,36580783379,9090,4696415
4,5,기술자들,2014-12-24,12.4%,1.2%,30367,28781000,19736744683,3760,2544717
5,6,워킹걸,2015-01-07,10.1%,0.46%,11713,9121500,1085098979,1186,134144
6,7,개를 훔치는 완벽한 방법,2014-12-31,30.2%,0.18%,4423,9173700,1684918765,1337,221805
7,8,뽀로로 극장판 눈요정 마을 대모험,NaN,5.1%,0.13%,3275,721000,1269500700,167,254045
8,9,쿼바디스,2014-12-10,10.1%,0.09%,2168,1364400,141777300,219,18836
9,10,순천,2014-09-04,0.4%,0.06%,1415,10000,22832200,5,3610
10,11,파티51,2014-12-11,2.5%,0.05%,1170,210000,15143800,29,2037
11,12,목숨,2014-12-04,6.0%,0.04%,1076,466000,283397600,64,36867
12,12,그 사람 그 사랑 그 세상,2014-11-20,2.6%,0.04%,1053,176000,186986500,27,25215
13,12,설해,2015-01-08,2.4%,0.04%,962,183000,27419500,23,3653
14,15,더 테너 리리코 스핀토,2014-12-31,68.5%,0.02%,565,2859000,375039941,387,48526
15,15,상의원,2014-12-24,14.6%,0.02%,495,504000,6198263964,72,789628
16,15,카토 프로젝트,2014-04-17,0.3%,0.02%,600,4000,1918000,2,635
17,18,고양이 장례식,2015-01-15,98.3%,0.01%,178,1533000,11512600,175,1420
18,18,족구왕,2014-08-21,3.6%,0.01%,138,40000,359459000,5,45666
19,18,두 번째 엄마,2014-12-31,1.4%,0.01%,146,14000,1010000,2,239
20,18,못,2014-11-20,0.9%,0.01%,212,10000,16941600,2,2368
21,18,악사들,2014-12-04,0.9%,0.01%,212,12000,7733200,2,1372
22,23,카트,2014-11-13,27.3%,0%,110,236000,5924979433,30,813982
23,23,다이빙벨,2014-10-23,10.9%,0%,110,96000,341616500,12,49300
24,23,레드 툼,2015-07-09,6.9%,0%,102,35000,1257000,7,230
25,23,앙상블,2014-12-18,6.4%,0%,94,34000,6939500,6,900
26,23,자유의 언덕,2014-09-04,7.9%,0%,76,48000,310619827,6,38286
27,23,"제자, 옥한흠",2014-10-30,6.6%,0%,76,40000,359310200,5,48904
28,23,숫호구,2014-08-07,3.9%,0%,102,22000,16348000,4,2117
29,23,춘하추동 로맨스,2014-12-04,2.9%,0%,102,21000,8119800,3,1200
30,23,독립영화발표회(251회) - 박영석 프로그래머 추천전,NaN,0.0%,0%,125,0,0,0,0

In [ ]:
# 일별 상영점유율 http://www.kobis.or.kr/kobis/business/stat/boxs/findDailyShowTicketList.do

NAME = 'findDailyShowTicketList'
URL = f'http://www.kobis.or.kr/kobis/business/stat/boxs/{NAME}.do'

date = datetime.date(2015, 1, 1)

while date < datetime.date(2019, 11, 1):
    start_date = date.isoformat()
    end_date = (date + datetime.timedelta(days=6)).isoformat()
    print(start_date, '~', end_date)
    os.system(f'curl "{URL}?loadEnd=0&dmlMode=excel&' \
              f'startDate={start_date}&endDate={end_date}&repNationCd=1"' \
              f' > 일별상영점유율-{start_date}.html')
    date += datetime.timedelta(days=7)

2015-01-01 ~ 2015-01-07
2015-01-08 ~ 2015-01-14
2015-01-15 ~ 2015-01-21
2015-01-22 ~ 2015-01-28
2015-01-29 ~ 2015-02-04
2015-02-05 ~ 2015-02-11
2015-02-12 ~ 2015-02-18
2015-02-19 ~ 2015-02-25
2015-02-26 ~ 2015-03-04
2015-03-05 ~ 2015-03-11
2015-03-12 ~ 2015-03-18
2015-03-19 ~ 2015-03-25
2015-03-26 ~ 2015-04-01
2015-04-02 ~ 2015-04-08
2015-04-09 ~ 2015-04-15
2015-04-16 ~ 2015-04-22
2015-04-23 ~ 2015-04-29
2015-04-30 ~ 2015-05-06
2015-05-07 ~ 2015-05-13
2015-05-14 ~ 2015-05-20
2015-05-21 ~ 2015-05-27
2015-05-28 ~ 2015-06-03
2015-06-04 ~ 2015-06-10
2015-06-11 ~ 2015-06-17
2015-06-18 ~ 2015-06-24
2015-06-25 ~ 2015-07-01
2015-07-02 ~ 2015-07-08
2015-07-09 ~ 2015-07-15
2015-07-16 ~ 2015-07-22
2015-07-23 ~ 2015-07-29
2015-07-30 ~ 2015-08-05
2015-08-06 ~ 2015-08-12
2015-08-13 ~ 2015-08-19
2015-08-20 ~ 2015-08-26
2015-08-27 ~ 2015-09-02
2015-09-03 ~ 2015-09-09
2015-09-10 ~ 2015-09-16
2015-09-17 ~ 2015-09-23
2015-09-24 ~ 2015-09-30
2015-10-01 ~ 2015-10-07
2015-10-08 ~ 2015-10-14
2015-10-15 ~ 2015-10-21
2015-10-22 ~ 2015-10-28
2015-10-29 ~ 2015-11-04
2015-11-05 ~ 2015-11-11
2015-11-12 ~ 2015-11-18
2015-11-19 ~ 2015-11-25
2015-11-26 ~ 2015-12-02
2015-12-03 ~ 2015-12-09
2015-12-10 ~ 2015-12-16
2015-12-17 ~ 2015-12-23
2015-12-24 ~ 2015-12-30
2015-12-31 ~ 2016-01-06
2016-01-07 ~ 2016-01-13
2016-01-14 ~ 2016-01-20
2016-01-21 ~ 2016-01-27
2016-01-28 ~ 2016-02-03
2016-02-04 ~ 2016-02-10
2016-02-11 ~ 2016-02-17
2016-02-18 ~ 2016-02-24
2016-02-25 ~ 2016-03-02
2016-03-03 ~ 2016-03-09
2016-03-10 ~ 2016-03-16
2016-03-17 ~ 2016-03-23
2016-03-24 ~ 2016-03-30
2016-03-31 ~ 2016-04-06
2016-04-07 ~ 2016-04-13
2016-04-14 ~ 2016-04-20
2016-04-21 ~ 2016-04-27
2016-04-28 ~ 2016-05-04
2016-05-05 ~ 2016-05-11
2016-05-12 ~ 2016-05-18
2016-05-19 ~ 2016-05-25
2016-05-26 ~ 2016-06-01
2016-06-02 ~ 2016-06-08
2016-06-09 ~ 2016-06-15
2016-06-16 ~ 2016-06-22
2016-06-23 ~ 2016-06-29
2016-06-30 ~ 2016-07-06
2016-07-07 ~ 2016-07-13
2016-07-14 ~ 2016-07-20
2016-07-21 ~ 2016-07-27
2016-07-28 ~ 2016-08-03
2016-08-04 ~ 2016-08-10
2016-08-11 ~ 2016-08-17
2016-08-18 ~ 2016-08-24
2016-08-25 ~ 2016-08-31
2016-09-01 ~ 2016-09-07
2016-09-08 ~ 2016-09-14
2016-09-15 ~ 2016-09-21
2016-09-22 ~ 2016-09-28
2016-09-29 ~ 2016-10-05
2016-10-06 ~ 2016-10-12
2016-10-13 ~ 2016-10-19
2016-10-20 ~ 2016-10-26
2016-10-27 ~ 2016-11-02
2016-11-03 ~ 2016-11-09
2016-11-10 ~ 2016-11-16
2016-11-17 ~ 2016-11-23
2016-11-24 ~ 2016-11-30
2016-12-01 ~ 2016-12-07
2016-12-08 ~ 2016-12-14
2016-12-15 ~ 2016-12-21
2016-12-22 ~ 2016-12-28
2016-12-29 ~ 2017-01-04
2017-01-05 ~ 2017-01-11
2017-01-12 ~ 2017-01-18
2017-01-19 ~ 2017-01-25
2017-01-26 ~ 2017-02-01
2017-02-02 ~ 2017-02-08
2017-02-09 ~ 2017-02-15
2017-02-16 ~ 2017-02-22
2017-02-23 ~ 2017-03-01
2017-03-02 ~ 2017-03-08
2017-03-09 ~ 2017-03-15
2017-03-16 ~ 2017-03-22
2017-03-23 ~ 2017-03-29
2017-03-30 ~ 2017-04-05
2017-04-06 ~ 2017-04-12
2017-04-13 ~ 2017-04-19
2017-04-20 ~ 2017-04-26
2017-04-27 ~ 2017-05-03
2017-05-04 ~ 2017-05-10
2017-05-11 ~ 2017-05-17
2017-05-18 ~ 2017-05-24
2017-05-25 ~ 2017-05-31
2017-06-01 ~ 2017-06-07
2017-06-08 ~ 2017-06-14
2017-06-15 ~ 2017-06-21
2017-06-22 ~ 2017-06-28
2017-06-29 ~ 2017-07-05
2017-07-06 ~ 2017-07-12
2017-07-13 ~ 2017-07-19
2017-07-20 ~ 2017-07-26
2017-07-27 ~ 2017-08-02
2017-08-03 ~ 2017-08-09
2017-08-10 ~ 2017-08-16
2017-08-17 ~ 2017-08-23
2017-08-24 ~ 2017-08-30
2017-08-31 ~ 2017-09-06
2017-09-07 ~ 2017-09-13
2017-09-14 ~ 2017-09-20
2017-09-21 ~ 2017-09-27
2017-09-28 ~ 2017-10-04
2017-10-05 ~ 2017-10-11
2017-10-12 ~ 2017-10-18
2017-10-19 ~ 2017-10-25
2017-10-26 ~ 2017-11-01
2017-11-02 ~ 2017-11-08
2017-11-09 ~ 2017-11-15
2017-11-16 ~ 2017-11-22
2017-11-23 ~ 2017-11-29
2017-11-30 ~ 2017-12-06
2017-12-07 ~ 2017-12-13
2017-12-14 ~ 2017-12-20
2017-12-21 ~ 2017-12-27
2017-12-28 ~ 2018-01-03
2018-01-04 ~ 2018-01-10
2018-01-11 ~ 2018-01-17
2018-01-18 ~ 2018-01-24
2018-01-25 ~ 2018-01-31
2018-02-01 ~ 2018-02-07
2018-02-08 ~ 2018-02-14
2018-02-15 ~ 2018-02-21
2018-02-22 ~ 2018-02-28
2018-03-01 ~ 2018-03-07
2018-03-08 ~ 2018-03-14
2018-03-15 ~ 2018-03-21
2018-03-22 ~ 2018-03-28
2018-03-29 ~ 2018-04-04
2018-04-05 ~ 2018-04-11
2018-04-12 ~ 2018-04-18
2018-04-19 ~ 2018-04-25
2018-04-26 ~ 2018-05-02
2018-05-03 ~ 2018-05-09
2018-05-10 ~ 2018-05-16
2018-05-17 ~ 2018-05-23
2018-05-24 ~ 2018-05-30
2018-05-31 ~ 2018-06-06
2018-06-07 ~ 2018-06-13
2018-06-14 ~ 2018-06-20
2018-06-21 ~ 2018-06-27
2018-06-28 ~ 2018-07-04
2018-07-05 ~ 2018-07-11
2018-07-12 ~ 2018-07-18
2018-07-19 ~ 2018-07-25
2018-07-26 ~ 2018-08-01
2018-08-02 ~ 2018-08-08
2018-08-09 ~ 2018-08-15
2018-08-16 ~ 2018-08-22
2018-08-23 ~ 2018-08-29
2018-08-30 ~ 2018-09-05
2018-09-06 ~ 2018-09-12
2018-09-13 ~ 2018-09-19
2018-09-20 ~ 2018-09-26
2018-09-27 ~ 2018-10-03
2018-10-04 ~ 2018-10-10
2018-10-11 ~ 2018-10-17
2018-10-18 ~ 2018-10-24
2018-10-25 ~ 2018-10-31
2018-11-01 ~ 2018-11-07
2018-11-08 ~ 2018-11-14
2018-11-15 ~ 2018-11-21
2018-11-22 ~ 2018-11-28
2018-11-29 ~ 2018-12-05
2018-12-06 ~ 2018-12-12
2018-12-13 ~ 2018-12-19
2018-12-20 ~ 2018-12-26
2018-12-27 ~ 2019-01-02
2019-01-03 ~ 2019-01-09
2019-01-10 ~ 2019-01-16
2019-01-17 ~ 2019-01-23
2019-01-24 ~ 2019-01-30
2019-01-31 ~ 2019-02-06
2019-02-07 ~ 2019-02-13
2019-02-14 ~ 2019-02-20
2019-02-21 ~ 2019-02-27
2019-02-28 ~ 2019-03-06
2019-03-07 ~ 2019-03-13

In [ ]:
# 일별 스크린점유율 http://www.kobis.or.kr/kobis/business/stat/boxs/findDailyScreenTicketList.do

In [ ]:
http://www.kobis.or.kr/kobis/business/mast/thea/findShowHistorySc.do
http://www.kobis.or.kr/kobis/business/mast/thea/findShowHistoryScXls.do?theaCd=001123&theaArea=Y&showStartDt=2019-11-19&showEndDt=2019-11-26"


NAME = 'findDailyShowTicketList'
URL = f'http://www.kobis.or.kr/kobis/business/mast/thea/findShowHistorySc.do'

date = datetime.date(2015, 1, 1)

while date < datetime.date(2019, 11, 1):
    start_date = date.isoformat()
    end_date = (date + datetime.timedelta(days=6)).isoformat()
    print(start_date, '~', end_date)
    os.system(f'curl "{URL}?loadEnd=0&dmlMode=excel&' \
              f'startDate={start_date}&endDate={end_date}&repNationCd=1"' \
              f' > 일별상영점유율-{start_date}.html')
    date += datetime.timedelta(days=7)