In [67]:
import os
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('float_format', '{:f}'.format)

# warning message 제거
import warnings
warnings.filterwarnings('ignore')

In [2]:
theater = pd.read_csv('theaters_191128.csv')
theater.sample()

,광역단체,기초단체,영화상영관코드,영화상영관명,총 스크린수,총 좌석수,필름 상영관수,2D 상영관수,3D 상영관수,4D 상영관수,IMAX 상영관수,상설여부,특별관운영여부,가입여부,전송사업자명,개관일,영업상태,운영형태,주소,전화번호,홈페이지
537,대구시,수성구,12044,CGV 대구수성,4,804,0,4,2,0,0,상설,nan,가입,CJ올리브네트웍스(주),2013-05-23,영업,직영,대구광역시 수성구 범물동 1273 번지,1544-1122,NaN

In [3]:
theater['영화상영관코드'].dtype

dtype('int64')

In [4]:
theater['영화상영관코드'] = theater['영화상영관코드'].astype(str).apply(lambda x: ('0'+'0'+x)[-6:])
theater['영화상영관코드']

0      003208
1      014017
2      002253
3      013035
4      002116
5      001163
6      011063
7      002250
8      001066
9      001274
10     006079
11     012020
12     002179
13     003039
14     004017
15     001205
16     011053
17     001272
18     011067
19     004047
20     001273
21     012033
22     001088
23     002252
24     001271
25     001150
26     002251
27     013034
28     006083
29     003211
30     002061
31     002087
32     014015
33     015062
34     004040
35     002249
36     011019
37     001241
38     012055
39     009056
40     014003
41     009025
42     009066
43     004041
44     009062
45     005061
46     009059
47     009057
48     008225
49     009051
50     008224
51     015050
52     008050
53     001221
54     008047
55     008043
56     006082
57     006080
58     007081
59     003210
60     006074
61     003207
62     003205
63     003203
64     007074
65     007073
66     006066
67     003201
68     003200
69     003199
70     003197
71     016035
72     002248
73     002154
74     003214
75     006078
76     006068
77     003213
78     002065
79     011044
80     001186
81     002041
82     011054
83     011057
84     011038
85     004025
86     015023
87     001217
88     001121
89     001224
90     002219
91     004024
92     008021
93     006030
94     006043
95     015019
96     016020
97     001098
98     003031
99     001101
100    007084
101    016047
102    002232
103    009058
104    001222
105    006047
106    002176
107    003046
108    001203
109    001269
110    002113
111    017039
112    002045
113    001036
114    001270
115    002185
116    011027
117    013030
118    012050
119    016041
120    001194
121    001123
122    015059
123    010011
124    001127
125    001083
126    001017
127    004036
128    005043
129    007025
130    002125
131    008226
132    001034
133    002118
134    001156
135    001236
136    002234
137    002057
138    013026
139    012034
140    007031
141    016015
142    015024
143    008051
144    007052
145    015005
146    002126
147    002150
148    011007
149    016027
150    002075
151    013012
152    006035
153    001192
154    002006
155    001216
156    014013
157    002010
158    011046
159    001154
160    001158
161    001245
162    001128
163    001016
164    001230
165    001111
166    013033
167    004046
168    002042
169    007083
170    002237
171    009053
172    002247
173    009029
174    007079
175    004044
176    001100
177    001148
178    001197
179    001231
180    008016
181    008052
182    004038
183    010018
184    005053
185    005051
186    011066
187    009030
188    005064
189    013017
190    012006
191    011052
192    011051
193    001080
194    015057
195    016022
196    016021
197    011026
198    002223
199    002172
200    001267
201    002102
202    007080
203    002210
204    004045
205    005027
206    009061
207    012035
208    004012
209    010002
210    001125
211    002228
212    002222
213    003025
214    012015
215    011025
216    014001
217    001071
218    012053
219    006077
220    006029
221    002230
222    002212
223    005060
224    002243
225    004043
226    005041
227    005049
228    005046
229    010016
230    008048
231    008231
232    008230
233    009050
234    009020
235    009064
236    009054
237    015056
238    015039
239    015020
240    015049
241    001057
242    001247
243    001106
244    001251
245    001257
246    011058
247    011045
248    011006
249    011034
250    007068
251    013029
252    016038
253    016046
254    006057
255    006069
256    007032
257    007076
258    007077
259    002200
260    002214
261    002233
262    002117
263    002011
264    002047
265    002183
266    002220
267    002246
268    006006
269    002235
270    002245
271    012054
272    004042
273    005057
274    005054
275    005055
276    005059
277    005047
278    005052
279    008227
280    008228
281    008049
282    009052
283    015035
284    001237
285    001062
286    001227
287    001149
288    001240
289    001248
290    001242
291    016044
292    006071
293    006019
294    006076
295    006073
296    007072
297    003029
298    003202
299    004014
300    004037
301    004001
302    005058
303    008024
304    009060
305    015061
306    015055
307    015053
308    015051
309    002244
310    015052
311    014009
312    001159
313    001151
314    001112
315    001030
316    001117
317    001243
318    001246
319    001003
320    011020
321    011062
322    011059
323    012051
324    006075
325    006065
326    006039
327    006070
328    007036
329    007078
330    007071
331    007069
332    002072
333    002127
334    002226
335    002097
336    002052
337    002218
338    002114
339    002007
340    002054
341    002122
342    002240
343    002180
344    002128
345    002229
346    003206
347    003204
348    001124
349    007082
350    005038
351    001228
352    012046
353    005023
354    010017
355    015044
356    006064
357    001196
358    001144
359    002224
360    001195
361    006036
362    002204
363    002225
364    002203
365    004039
366    002242
367    002241
368    003212
369    001164
370    007012
371    007062
372    007075
373    002184
374    002199
375    008034
376    008020
377    015058
378    015054
379    002036
380    002239
381    001268
382    002221
383    001239
384    012032
385    014014
386    001208
387    001104
388    001102
389    002217
390    002019
391    002106
392    001155
393    005045
394    002182
395    001244
396    002049
397    016036
398    002124
399    012014
400    004031
401    001198
402    011008
403    012048
404    011024
405    015036
406    002187
407    011009
408    002119
409    002035
410    002059
411    003042
412    012029
413    011056
414    011040
415    001226
416    013028
417    002238
418    013021
419    013007
420    011061
421    012042
422    001109
423    003024
424    007065
425    007066
426    001188
427    008232
428    008041
429    006038
430    002055
431    002208
432    016014
433    002050
434    002063
435    002085
436    005063
437    001126
438    013032
439    003043
440    006063
441    001122
442    001234
443    001202
444    001207
445    002068
446    001235
447    002175
448    002216
449    001258
450    015060
451    008223
452    002236
453    011065
454    012031
455    016045
456    007030
457    016040
458    001096
459    001225
460    009028
461    016037
462    001189
463    005026
464    011003
465    012022
466    005012
467    001146
468    012047
469    015017
470    016013
471    003198
472    002038
473    002211
474    002206
475    010010
476    007037
477    002231
478    015043
479    007064
480    003209
481    012045
482    001105
483    009055
484    002227
485    005056
486    016039
487    002202
488    016042
489    006062
490    008022
491    005034
492    002133
493    002149
494    012018
495    001107
496    001169
497    002037
498    001099
499    007020
500    002186
501    008042
502    001739
503     00432
504    002074
505    007063
506    015010
507    001191
508    012013
509    002151
510    002112
511    005039
512    002141
513    002189
514    001193
515    013027
516    001165
517    011039
518    012030
519    002205
520    002107
521    005021
522    009047
523    007056
524    005033
525    009048
526    014012
527    001166
528    011031
529    013019
530    012007
531    006020
532    011055
533    015042
534    002073
535    002142
536    012043
537    012044
538    003026
539    002040
540    002188
541    002169
542    015025
543    002190
544    002209
545    008023
546    001027
547    007055
548    002046
549    002048
550    001210
551    001103
552    002096
Name: 영화상영관코드, dtype: object

In [28]:
code = theater[['영화상영관코드', '영화상영관명', '개관일']]

In [6]:
uncrawled_theater = ['메가박스 세종',
 '롯데시네마 병점',
 '롯데시네마 인천터미널',
 '롯데시네마 독산',
 '메가박스 화곡',
 '영화의전당',
 'CGV 오산중앙',
 '롯데시네마 창원',
 '롯데시네마 대전둔산',
 '롯데시네마 전주평화',
 '롯데시네마 진주혁신',
 '메가박스군자',
 '롯데시네마 평촌_샤롯데',
 '메가박스 성수점',
 '메가박스 영종',
 '롯데시네마 대구광장',
 'CGV 순천',
 '롯데시네마 동부산(아울렛)',
 '롯데시네마 해운대',
 '롯데시네마 라페스타(일산)',
 'CGV 여수웅천',
 '메가박스 천안',
 '화성시문화재단 모두누림센터 누림아트홀',
 'CGV 울산신천',
 'CGV 용산아이파크몰',
 '롯데시네마 광주광산',
 '롯데시네마 주엽(일산)',
 '롯데시네마 부산본점(백화점)',
 '메가박스 구미강동',
 'CGV 송파',
 '롯데시네마 용인기흥',
 'CGV 영등포',
 '롯데시네마 마산터미널',
 '메가박스진천점',
 'CGV 목포평화광장',
 '이봄씨어터',
 '롯데시네마 진해',
 'CGV 청주(서문)',
 '롯데시네마 안성',
 '롯데시네마 청량리',
 '롯데시네마 대전관저',
 '메가박스송도',
 '롯데시네마 동래',
 '롯데시네마 부천(신중동역)',
 '롯데시네마 제주삼화',
 '양평시네마',
 '롯데시네마 진접']

In [29]:
code = code[code.isin({'영화상영관명':uncrawled_theater})['영화상영관명']]
len(code)

47

In [9]:
code 
# 최근 개관 1, 2, 3, 
# 9 메가박스 성수점 10/30

# 있음14, 22, 134, 160, 192

    영화상영관코드                영화상영관명
1    014017              CGV 울산신천
2    002253              CGV 오산중앙
3    013035            롯데시네마 대전관저
9    001274              메가박스 성수점
14   004017            CGV 청주(서문)
22   001088           CGV 용산아이파크몰
134  001156                CGV 송파
160  001158               CGV 영등포
192  011051                 영화의전당
215  011025             롯데시네마 해운대
233  009050              CGV 여수웅천
234  009020                CGV 순천
235  009064            CGV 목포평화광장
290  001242                 이봄씨어터
300  004037               메가박스진천점
305  015061               메가박스 영종
306  015055                메가박스송도
350  005038               메가박스 세종
351  001228               메가박스 화곡
353  005023               메가박스 천안
354  010017            롯데시네마 제주삼화
356  006064             메가박스 구미강동
369  001164             롯데시네마 청량리
370  007012              롯데시네마 창원
371  007062              롯데시네마 진해
372  007075            롯데시네마 진주혁신
373  002184              롯데시네마 진접
374  002199          롯데시네마 주엽(일산)
375  008034            롯데시네마 전주평화
377  015058           롯데시네마 인천터미널
381  001268                메가박스군자
406  002187        롯데시네마 부천(신중동역)
407  011009       롯데시네마 부산본점(백화점)
408  002119              롯데시네마 병점
410  002059        롯데시네마 라페스타(일산)
413  011056        롯데시네마 동부산(아울렛)
414  011040              롯데시네마 동래
415  001226              롯데시네마 독산
416  013028            롯데시네마 대전둔산
417  002238            롯데시네마 용인기흥
421  012042            롯데시네마 대구광장
444  001207              롯데시네마 안성
455  016045            롯데시네마 광주광산
484  002227  화성시문화재단 모두누림센터 누림아트홀
513  002189                 양평시네마
519  002205          롯데시네마 평촌_샤롯데
523  007056           롯데시네마 마산터미널

In [10]:
# 띄어쓰기 안된 것들 띄우기
code.loc[code['영화상영관명'].str.contains(' ') == False]

    영화상영관코드   영화상영관명
192  011051    영화의전당
290  001242    이봄씨어터
300  004037  메가박스진천점
306  015055   메가박스송도
381  001268   메가박스군자
513  002189    양평시네마

In [ ]:
code[code['영화상영관코드'] == '011051', '영화상영관명(변경)'] = '영화의 전당'
code[code['영화상영관코드'] == '011051', '영화상영관명(변경)'] = '영화의 전당'
code[code['영화상영관코드'] == '011051', '영화상영관명(변경)'] = '영화의 전당'

# 상영관정보 데이터 크롤링 
http://www.kobis.or.kr/kobis/business/mast/thea/findTheaterInfoList.do  

완료되었으므로 다시 돌릴 필요 없음. 슬랙에서 '상영관정보.zip'을 다운받아 이 노트북이 돌아가는 폴더에 압축 풀어주세요.

In [19]:
URL = f'http://www.kobis.or.kr/kobis/business/mast/thea/findTheaterCodeLayer.do'

In [57]:
for i, row in code.iterrows():
    theaCd = row['영화상영관코드']
    theaNm = row['영화상영관명'].strip().replace(' ', '%20').replace('(', '%28').replace(')', '%29')
    os.system(f'curl "{URL}?theaCd={theaCd}" > 상영관정보-{theaNm}.html')

# 상영내역 데이터 크롤링
http://www.kobis.or.kr/kobis/business/mast/thea/findShowHistorySc.do

In [10]:
URL = f'http://www.kobis.or.kr/kobis/business/mast/thea/findShowHistoryScXls.do'

In [13]:
code.iloc[36:]

    영화상영관코드                영화상영관명
414  011040              롯데시네마 동래
415  001226              롯데시네마 독산
416  013028            롯데시네마 대전둔산
417  002238            롯데시네마 용인기흥
421  012042            롯데시네마 대구광장
444  001207              롯데시네마 안성
455  016045            롯데시네마 광주광산
484  002227  화성시문화재단 모두누림센터 누림아트홀
513  002189                 양평시네마
519  002205          롯데시네마 평촌_샤롯데
523  007056           롯데시네마 마산터미널

In [29]:
code.loc[code['영화상영관명'] == '이봄씨어터', '영화상영관코드']

290    001242
Name: 영화상영관코드, dtype: object

In [66]:
# 완료 001156 CGV 송파-4 # 데이터 있음 # 파일이 없나?
# 완료 011051 영화의전당-1 # 데이터 있음 # 2018 9월26일 ~10월13일까지 없음 # 파일이 없나? # 날짜 나눠서 시도중
# 완료 001226 롯데시네마 독산-2 # 데이터 있음 # 파일이 없나?
# 2018 7월1일, 2019 2월17일 따로, 2019 2월 쪼개서 돌리기 + 2018, 016045 롯데시네마 광주광산-0, 1, (2, 3, 4) # 2018 3월 개관 # 데이터 있음 # 파일이 없나?
# 완료 2019 10월9일 ~ 14일까지 일별, 001242 이봄씨어터-0, 

# for i, row in code[37:].iterrows(): 
# row = code.iloc[36]
#     print(row['영화상영관명'])
#     if i == 0 : break
# row = code.iloc[4]

# for i, row in code[150:300].iterrows(): 
# for i, row in code[160:161].iterrows(): # 다시 다운로드 완료 # merge 완료
# for i, row in code[192:193].iterrows(): # 다시 다운로드 완료 # merge 완료
# for i, row in code[215:216].iterrows(): # 다시 다운로드 완료 # merge 해야함
# for i, row in code[233:236].iterrows(): # 다시 다운로드 완료 # merge 해야함
# for i, row in code[290:291].iterrows(): # 다시 다운로드 완료 # merge 해야함
# 안 받아진 파일    160, 192, 215, 233: 235, 290

# 일부 상영관의 데이터만 가져올 때는 code[n:m].iterrows() 로 바꾸고 n과 m에 인덱스 숫자를 넣음
# theaCd = row['영화상영관코드']
theaCd = '011051'
# theaNm = row['영화상영관명'].strip().replace(' ', '%20').replace('(', '%28').replace(')', '%29')
theaNm = '영화의전당'.strip().replace(' ', '%20').replace('(', '%28').replace(')', '%29')
# os.system(f'curl "{URL}?theaCd={theaCd}&showStartDt=2015-01-01&showEndDt=2019-10-31&choice=2&sTheaNm={theaNm}"' \
#           f' > 상영내역-{theaNm}.html')

# 연도별
# os.system(f'curl "{URL}?theaCd={theaCd}&showStartDt=2019-01-01&showEndDt=2019-10-31&choice=2&sTheaNm={theaNm}"' \
#           f' > 상영내역-{theaNm}.html')
# os.system(f'curl "{URL}?theaCd={theaCd}&showStartDt=2018-01-01&showEndDt=2018-12-31&choice=2&sTheaNm={theaNm}"' \
#           f' > 상영내역-{theaNm}-1.html')
# os.system(f'curl "{URL}?theaCd={theaCd}&showStartDt=2017-01-01&showEndDt=2017-12-31&choice=2&sTheaNm={theaNm}"' \
#           f' > 상영내역-{theaNm}-2.html')
# os.system(f'curl "{URL}?theaCd={theaCd}&showStartDt=2016-01-01&showEndDt=2016-12-31&choice=2&sTheaNm={theaNm}"' \
#           f' > 상영내역-{theaNm}-3.html')
# os.system(f'curl "{URL}?theaCd={theaCd}&showStartDt=2015-01-01&showEndDt=2015-12-31&choice=2&sTheaNm={theaNm}"' \
#           f' > 상영내역-{theaNm}-4.html')

# 월별
# os.system(f'curl "{URL}?theaCd={theaCd}&showStartDt=2018-01-01&showEndDt=2018-01-31&choice=2&sTheaNm={theaNm}"' \
#           f' > 상영내역-{theaNm}-1-0.html')
# os.system(f'curl "{URL}?theaCd={theaCd}&showStartDt=2018-02-01&showEndDt=2018-02-28&choice=2&sTheaNm={theaNm}"' \
#           f' > 상영내역-{theaNm}-1-1.html')
# os.system(f'curl "{URL}?theaCd={theaCd}&showStartDt=2018-03-01&showEndDt=2018-03-31&choice=2&sTheaNm={theaNm}"' \
#           f' > 상영내역-{theaNm}-1-2.html')
# os.system(f'curl "{URL}?theaCd={theaCd}&showStartDt=2018-04-01&showEndDt=2018-04-30&choice=2&sTheaNm={theaNm}"' \
#           f' > 상영내역-{theaNm}-1-3.html')
# os.system(f'curl "{URL}?theaCd={theaCd}&showStartDt=2018-05-01&showEndDt=2018-05-31&choice=2&sTheaNm={theaNm}"' \
#           f' > 상영내역-{theaNm}-1-4.html')
# os.system(f'curl "{URL}?theaCd={theaCd}&showStartDt=2018-06-01&showEndDt=2018-06-30&choice=2&sTheaNm={theaNm}"' \
#           f' > 상영내역-{theaNm}-1-5.html')
# os.system(f'curl "{URL}?theaCd={theaCd}&showStartDt=2018-07-01&showEndDt=2018-07-31&choice=2&sTheaNm={theaNm}"' \
#           f' > 상영내역-{theaNm}-1-6.html')
# os.system(f'curl "{URL}?theaCd={theaCd}&showStartDt=2018-08-01&showEndDt=2018-08-31&choice=2&sTheaNm={theaNm}"' \
#           f' > 상영내역-{theaNm}-1-7.html')
# os.system(f'curl "{URL}?theaCd={theaCd}&showStartDt=2018-09-01&showEndDt=2018-09-30&choice=2&sTheaNm={theaNm}"' \
#           f' > 상영내역-{theaNm}-1-8.html')
# os.system(f'curl "{URL}?theaCd={theaCd}&showStartDt=2018-10-01&showEndDt=2018-10-31&choice=2&sTheaNm={theaNm}"' \
#           f' > 상영내역-{theaNm}-1-9.html')
# os.system(f'curl "{URL}?theaCd={theaCd}&showStartDt=2018-11-01&showEndDt=2018-11-30&choice=2&sTheaNm={theaNm}"' \
#           f' > 상영내역-{theaNm}-1-10.html')
# os.system(f'curl "{URL}?theaCd={theaCd}&showStartDt=2018-12-01&showEndDt=2018-12-31&choice=2&sTheaNm={theaNm}"' \
#           f' > 상영내역-{theaNm}-1-11.html')
# 광주광산
# os.system(f'curl "{URL}?theaCd={theaCd}&showStartDt=2018-07-01&showEndDt=2018-07-01&choice=2&sTheaNm={theaNm}"' \
#           f' > 상영내역-{theaNm}-1-6-0.html')
# os.system(f'curl "{URL}?theaCd={theaCd}&showStartDt=2018-07-02&showEndDt=2018-07-31&choice=2&sTheaNm={theaNm}"' \
#           f' > 상영내역-{theaNm}-1-6-1.html')

# 광주광산
# os.system(f'curl "{URL}?theaCd={theaCd}&showStartDt=2019-02-01&showEndDt=2019-02-14&choice=2&sTheaNm={theaNm}"' \
#           f' > 상영내역-{theaNm}-0-1-0.html')
# os.system(f'curl "{URL}?theaCd={theaCd}&showStartDt=2019-02-15&showEndDt=2019-02-15&choice=2&sTheaNm={theaNm}"' \
#           f' > 상영내역-{theaNm}-0-1-1.html')
# os.system(f'curl "{URL}?theaCd={theaCd}&showStartDt=2019-02-16&showEndDt=2019-02-16&choice=2&sTheaNm={theaNm}"' \
#           f' > 상영내역-{theaNm}-0-1-2.html')
# os.system(f'curl "{URL}?theaCd={theaCd}&showStartDt=2019-02-17&showEndDt=2019-02-17&choice=2&sTheaNm={theaNm}"' \
#           f' > 상영내역-{theaNm}-0-1-3.html')
# os.system(f'curl "{URL}?theaCd={theaCd}&showStartDt=2019-02-18&showEndDt=2019-02-28&choice=2&sTheaNm={theaNm}"' \
#           f' > 상영내역-{theaNm}-0-1-4.html')
# 이봄씨어터
# os.system(f'curl "{URL}?theaCd={theaCd}&showStartDt=2019-10-01&showEndDt=2019-10-08&choice=2&sTheaNm={theaNm}"' \
#           f' > 상영내역-{theaNm}-0-9-0.html')
# os.system(f'curl "{URL}?theaCd={theaCd}&showStartDt=2019-10-09&showEndDt=2019-10-09&choice=2&sTheaNm={theaNm}"' \
#           f' > 상영내역-{theaNm}-0-9-1.html')
# os.system(f'curl "{URL}?theaCd={theaCd}&showStartDt=2019-10-10&showEndDt=2019-10-10&choice=2&sTheaNm={theaNm}"' \
#           f' > 상영내역-{theaNm}-0-9-2.html')
# os.system(f'curl "{URL}?theaCd={theaCd}&showStartDt=2019-10-11&showEndDt=2019-10-11&choice=2&sTheaNm={theaNm}"' \
#           f' > 상영내역-{theaNm}-0-9-3.html')
# os.system(f'curl "{URL}?theaCd={theaCd}&showStartDt=2019-10-12&showEndDt=2019-10-12&choice=2&sTheaNm={theaNm}"' \
#           f' > 상영내역-{theaNm}-0-9-4.html')
# os.system(f'curl "{URL}?theaCd={theaCd}&showStartDt=2019-10-13&showEndDt=2019-10-13&choice=2&sTheaNm={theaNm}"' \
#           f' > 상영내역-{theaNm}-0-9-5.html')
# os.system(f'curl "{URL}?theaCd={theaCd}&showStartDt=2019-10-14&showEndDt=2019-10-14&choice=2&sTheaNm={theaNm}"' \
#           f' > 상영내역-{theaNm}-0-9-6.html')
# os.system(f'curl "{URL}?theaCd={theaCd}&showStartDt=2019-10-15&showEndDt=2019-10-31&choice=2&sTheaNm={theaNm}"' \
#           f' > 상영내역-{theaNm}-0-9-7.html')
# 송파
# os.system(f'curl "{URL}?theaCd={theaCd}&showStartDt=2015-11-01&showEndDt=2015-11-21&choice=2&sTheaNm={theaNm}"' \
#           f' > 상영내역-{theaNm}-4-10-0.html')
# os.system(f'curl "{URL}?theaCd={theaCd}&showStartDt=2015-11-22&showEndDt=2015-11-22&choice=2&sTheaNm={theaNm}"' \
#           f' > 상영내역-{theaNm}-4-10-1.html')
# os.system(f'curl "{URL}?theaCd={theaCd}&showStartDt=2015-11-23&showEndDt=2015-11-23&choice=2&sTheaNm={theaNm}"' \
#           f' > 상영내역-{theaNm}-4-10-2.html')
# os.system(f'curl "{URL}?theaCd={theaCd}&showStartDt=2015-11-24&showEndDt=2015-11-24&choice=2&sTheaNm={theaNm}"' \
#           f' > 상영내역-{theaNm}-4-10-3.html')
# os.system(f'curl "{URL}?theaCd={theaCd}&showStartDt=2015-11-25&showEndDt=2015-11-30&choice=2&sTheaNm={theaNm}"' \
#           f' > 상영내역-{theaNm}-4-10-4.html')
# 영화의전당
# os.system(f'curl "{URL}?theaCd={theaCd}&showStartDt=2018-10-14&showEndDt=2018-12-31&choice=2&sTheaNm={theaNm}"' \
#           f' > 상영내역-{theaNm}-1-1.html')
os.system(f'curl "{URL}?theaCd={theaCd}&showStartDt=2018-03-08&showEndDt=2018-03-31&choice=2&sTheaNm={theaNm}"' \
          f' > 상영내역-{theaNm}-1-0-2.html')

0

In [26]:
pd.read_html('상영내역-롯데시네마%20광주광산-1-6-0.html')[1].sample()

ValueError: No tables found

In [ ]:
# 에러

# CGV 송파-4 # 데이터 있음 # 파일이 없나?
# 영화의전당-1 # 데이터 있음 # 10월 없음 # 파일이 없나?
# 롯데시네마 독산-2 # 데이터 있음 # 파일이 없나?
# 롯데시네마 광주광산-0, 1, (2, 3, 4) # 2018 개관 # 데이터 있음 # 파일이 없나?
# 이봄씨어터-0, (3, 4) # 2017 개관 # 0만 데이터 있음 # 아예 파일이 없나?

# 화성시문화재단 모두누림센터 누림아트홀-0, 1, 2, 3, 4 개관일 확인하기 # kobis 에 데이터 없음
# 양평시네마-0, 1, 2, 3, 4 # 개관일 확인하기 # kobis 에 데이터 없음

# CGV 목포평화광장-2, 3, 4 # 2018 개관 # 완료
# 메가박스 영종-2, 3, 4 # 2018 개관 # 완료
# 메가박스송도-3, 4 # 2017 개관 # 완료
# 롯데시네마 제주삼화-2, 3, 4 # 2018 개관 # 완료
# 롯데시네마 진주혁신-4 # 2016 개관 # 완료
# 롯데시네마 인천터미널-3, 4 # 2017 개관 # 완료
# 메가박스 군자-2, 3, 4 # 2018 개관 # 완료
# 롯데시네마 용인기흥-2, 3, 4 # 2018 개관 # 완료
# 메가박스 진천점-4 9kb 확인필요 # 맞게 들어왔을듯 # 완료

In [24]:
pd.read_html('상영내역-롯데시네마%20광주광산-1.html')[1].sample()

ValueError: No tables found

# 크롤링 오류났던 상영관 데이터 쪼개서 받아서 concat
001156 CGV 송파-4 

011051 영화의전당-1 

001226 롯데시네마 독산-2 

016045 롯데시네마 광주광산-0, 1, (2, 3, 4) # 2018 3월 개관  
- 2018 7월1일, 2019 2월17일 따로, 2019 2월 쪼개서 돌리기 + 2018, 

001242 이봄씨어터-0,  완료 2019 10월9일 ~ 14일까지 일별,

In [130]:
data = pd.read_csv('상영내역-영화의전당.csv')
print(data.shape)
data.sample()

(4958, 10)

,1회,2회,3회,4회,5회,6회,7회,8회,상영관,상영일자
3885,NaN,"12:50, 레이디 수잔(디지털), 7,000원","14:50, 라라랜드(디지털), 7,000원","17:20, 나, 다니엘 블레이크(디지털), 7,000원","19:50, 커튼콜(디지털), 7,000원",NaN,NaN,NaN,소극장,2016-12-13

In [136]:
df['상영일자'].value_counts()

2019-02-26    5
2017-07-31    5
2016-12-16    5
2018-04-20    5
2017-02-10    5
2019-05-03    5
2017-03-24    5
2016-11-28    5
2016-04-14    5
2018-07-28    5
2018-02-17    5
2018-02-15    5
2019-02-02    5
2018-06-15    5
2019-07-26    5
2018-06-16    5
2017-07-26    5
2017-02-26    5
2019-03-31    5
2017-01-14    5
2018-08-21    5
2018-08-04    5
2016-02-05    5
2017-06-09    5
2019-02-09    5
2017-03-11    5
2016-03-21    5
2017-04-21    5
2016-09-14    5
2019-09-15    5
2018-01-04    5
2017-06-11    5
2016-05-20    5
2017-06-10    5
2018-08-10    5
2018-03-11    5
2017-07-06    5
2018-03-09    5
2019-09-12    5
2018-02-18    5
2019-08-04    5
2019-05-12    5
2018-02-21    5
2018-02-02    5
2019-02-08    5
2016-09-02    5
2018-06-24    5
2019-02-05    5
2018-12-25    5
2017-07-01    5
2019-02-07    5
2016-03-22    5
2016-03-23    5
2017-03-08    5
2019-02-16    5
2019-06-20    5
2017-08-09    5
2018-01-01    5
2019-04-20    5
2019-03-06    5
2019-03-15    5
2017-07-15    5
2019-08-10    5
2018-02-16    5
2016-08-27    5
2017-06-23    5
2017-02-02    5
2018-01-08    5
2019-03-07    5
2016-08-28    5
2017-01-28    5
2016-12-17    5
2016-12-09    5
2017-06-21    5
2016-11-11    5
2017-02-27    5
2019-07-25    5
2018-01-12    5
2017-07-07    5
2017-03-09    5
2017-08-15    5
2017-04-22    5
2016-07-31    5
2018-04-21    5
2019-07-20    5
2019-03-13    5
2017-04-23    5
2017-01-01    5
2017-08-02    5
2017-07-03    5
2016-09-16    5
2019-04-21    5
2018-02-06    5
2018-08-11    5
2018-06-21    5
2017-06-30    5
2019-09-13    5
2016-09-13    5
2018-03-08    5
2016-01-30    5
2017-02-17    5
2016-01-29    5
2016-02-10    5
2018-02-09    5
2019-02-03    5
2016-08-14    5
2018-06-22    5
2017-01-02    5
2019-05-04    5
2018-01-09    5
2017-02-01    5
2016-09-12    5
2017-02-04    5
2018-02-25    5
2019-02-10    5
2019-06-23    5
2018-01-06    5
2018-01-07    5
2016-01-31    5
2016-06-19    5
2018-09-16    5
2019-02-06    5
2017-07-09    5
2017-03-01    5
2019-07-24    5
2016-09-18    5
2017-06-08    5
2017-03-19    5
2017-06-25    5
2017-06-22    5
2017-08-14    5
2019-04-05    5
2018-01-10    5
2018-03-15    5
2017-05-12    5
2017-07-18    5
2016-04-16    5
2019-03-02    5
2018-02-10    5
2016-08-15    5
2017-01-22    5
2019-02-04    5
2016-08-25    5
2017-12-03    5
2016-11-12    5
2017-08-06    5
2016-03-20    5
2018-01-11    5
2018-01-02    5
2017-01-07    5
2016-12-18    5
2019-05-02    5
2017-02-16    5
2017-07-02    5
2018-07-13    5
2016-04-13    5
2016-07-02    5
2016-12-10    5
2017-12-02    5
2019-03-05    5
2018-01-14    5
2016-02-08    5
2017-07-04    5
2019-04-19    5
2017-02-12    5
2017-07-14    5
2018-06-23    5
2017-12-10    5
2017-01-29    5
2016-04-15    5
2019-03-27    5
2018-08-12    5
2017-08-05    5
2017-02-11    5
2019-05-11    5
2017-12-15    5
2018-03-13    5
2017-03-10    5
2017-03-18    5
2018-08-05    5
2017-03-05    5
2017-08-03    5
2017-08-11    5
2016-11-13    5
2017-01-30    5
2017-02-19    5
2016-02-01    5
2019-09-14    5
2016-02-12    5
2016-04-09    5
2016-02-09    5
2017-03-12    5
2019-07-27    5
2018-02-03    5
2018-02-07    5
2018-01-03    5
2016-08-23    5
2018-08-06    5
2017-04-15    5
2019-07-19    5
2017-06-28    5
2019-03-29    5
2016-09-17    5
2019-03-16    5
2018-08-08    5
2017-07-05    5
2019-03-17    5
2016-07-01    5
2017-01-21    5
2019-05-05    5
2017-01-27    5
2016-02-06    5
2016-11-29    5
2016-07-03    5
2018-07-21    5
2016-03-12    5
2018-01-13    5
2018-05-13    5
2018-08-03    5
2016-05-04    5
2017-02-05    5
2017-01-31    5
2017-01-06    5
2018-03-23    5
2019-06-21    5
2019-04-04    5
2016-04-18    5
2017-08-13    5
2018-07-14    5
2018-03-16    5
2017-02-18    5
2016-09-15    5
2018-02-05    5
2017-06-24    5
2016-04-19    5
2018-07-29    5
2019-05-10    5
2016-05-22    5
2019-03-30    5
2017-07-28    5
2017-08-01    5
2019-07-28    5
2018-03-14    5
2016-05-21    5
2017-07-27    5
2018-08-02    5
2017-05-13    5
2017-10-01    5
2016-08-12    5
2017-07-29    5
2018-06-17    5
2017-02-03    5
2016-12-11    5
2017-07-08    5
2018-01-05    5
2018-12-08    5
2017-03-17    5
2017-01-15    5
2016-03-11    5
2016-05-08    5
2016-05-19    5
2017-08-04    5
2016-04-17    5
2016-02-07    5
2017-01-08    5
2016-02-02    5
2016-08-24    5
2016-08-13    5
2017-01-09    5
2016-08-26    5
2017-08-12    5
2019-03-01    5
2017-04-16    5
2019-03-14    5
2019-03-03    5
2018-03-12    5
2016-04-10    5
2019-06-22    5
2018-04-01    4
2018-03-10    4
2016-03-29    4
2017-12-06    4
2018-06-11    4
2018-04-22    4
2019-07-04    4
2017-09-24    4
2017-06-29    4
2016-09-20    4
2018-04-11    4
2016-11-21    4
2018-01-18    4
2019-02-15    4
2018-04-16    4
2018-10-17    4
2016-10-31    4
2019-10-15    4
2016-05-24    4
2016-12-05    4
2017-05-11    4
2019-08-14    4
2019-10-14    4
2019-05-24    4
2018-04-07    4
2019-01-02    4
2017-03-16    4
2019-07-30    4
2016-07-22    4
2018-01-24    4
2017-09-03    4
2018-10-16    4
2017-01-26    4
2018-02-27    4
2018-12-11    4
2018-02-08    4
2019-10-19    4
2016-03-26    4
2019-03-22    4
2017-05-06    4
2018-10-15    4
2016-06-27    4
2017-12-09    4
2017-01-04    4
2017-12-05    4
2019-09-07    4
2019-01-19    4
2019-05-06    4
2019-09-09    4
2019-02-17    4
2018-09-09    4
2017-06-17    4
2016-02-14    4
2018-11-24    4
2019-10-23    4
2018-10-30    4
2019-01-05    4
2019-03-20    4
2016-11-01    4
2018-05-01    4
2016-10-17    4
2017-09-29    4
2018-05-26    4
2018-08-29    4
2016-12-14    4
2016-12-01    4
2016-05-05    4
2017-09-19    4
2019-05-27    4
2017-12-24    4
2018-09-03    4
2016-04-05    4
2018-11-18    4
2018-11-20    4
2016-08-31    4
2016-07-10    4
2018-03-25    4
2017-03-23    4
2017-12-13    4
2017-05-15    4
2017-02-14    4
2018-09-06    4
2018-11-28    4
2017-09-20    4
2017-06-13    4
2019-01-16    4
2019-01-28    4
2017-01-20    4
2016-07-29    4
2019-08-02    4
2016-11-27    4
2017-12-18    4
2016-10-19    4
2016-07-11    4
2017-04-02    4
2019-04-02    4
2017-08-17    4
2019-01-31    4
2019-06-16    4
2019-03-23    4
2016-07-07    4
2017-01-13    4
2016-01-02    4
2017-11-22    4
2018-12-06    4
2018-07-10    4
2019-05-18    4
2018-09-01    4
2017-03-04    4
2018-05-28    4
2019-09-01    4
2016-05-16    4
2017-02-06    4
2019-02-27    4
2019-06-12    4
2019-08-24    4
2017-05-29    4
2018-02-13    4
2018-08-20    4
2016-07-25    4
2019-02-25    4
2017-10-02    4
2016-06-13    4
2016-09-09    4
2016-12-30    4
2016-04-29    4
2016-09-07    4
2019-08-19    4
2016-03-16    4
2017-12-23    4
2017-11-14    4
2018-12-01    4
2018-06-14    4
2016-11-22    4
2016-11-09    4
2018-11-04    4
2019-04-08    4
2018-11-29    4
2018-01-27    4
2018-08-22    4
2018-01-29    4
2017-02-28    4
2017-08-20    4
2018-07-18    4
2017-09-09    4
2016-11-15    4
2018-10-25    4
2017-08-08    4
2018-10-27    4
2017-05-01    4
2018-12-18    4
2018-12-12    4
2019-07-08    4
2016-08-16    4
2018-12-21    4
2019-01-30    4
2016-01-20    4
2016-12-04    4
2016-08-29    4
2018-12-03    4
2016-04-30    4
2018-12-05    4
2017-02-09    4
2018-11-03    4
2017-10-03    4
2019-03-25    4
2016-12-08    4
2016-06-11    4
2016-09-03    4
2016-12-21    4
2016-04-03    4
2016-07-30    4
2017-08-21    4
2018-04-13    4
2016-07-27    4
2016-06-15    4
2016-08-09    4
2016-04-20    4
2017-09-14    4
2016-12-24    4
2017-05-19    4
2016-06-06    4
2018-09-02    4
2018-05-25    4
2018-10-28    4
2017-03-13    4
2016-07-16    4
2018-03-26    4
2016-06-24    4
2018-08-13    4
2018-10-19    4
2019-01-26    4
2017-04-06    4
2018-04-08    4
2019-01-10    4
2018-04-04    4
2018-11-27    4
2017-11-01    4
2018-06-02    4
2017-09-26    4
2017-09-02    4
2017-09-18    4
2016-03-14    4
2017-03-07    4
2017-09-23    4
2019-01-15    4
2019-07-16    4
2016-06-29    4
2019-08-16    4
2019-10-29    4
2017-11-28    4
2017-04-19    4
2016-12-07    4
2017-11-06    4
2016-08-08    4
2016-06-26    4
2019-09-02    4
2017-05-20    4
2018-08-01    4
2016-05-18    4
2016-11-02    4
2018-10-23    4
2016-09-10    4
2018-11-12    4
2017-06-06    4
2017-03-27    4
2019-01-07    4
2017-04-09    4
2017-09-28    4
2019-09-03    4
2018-01-19    4
2016-06-25    4
2019-05-01    4
2018-12-23    4
2016-12-13    4
2018-04-03    4
2016-05-23    4
2017-03-22    4
2017-08-19    4
2019-08-08    4
2017-01-10    4
2016-10-18    4
2019-03-04    4
2017-11-16    4
2019-10-24    4
2017-02-22    4
2016-06-18    4
2016-06-16    4
2016-07-08    4
2017-12-07    4
2018-06-06    4
2016-11-14    4
2019-04-22    4
2018-06-30    4
2016-11-30    4
2017-02-07    4
2016-03-18    4
2019-07-15    4
2018-03-18    4
2016-07-28    4
2019-06-24    4
2016-05-25    4
2018-10-29    4
2018-08-23    4
2016-09-06    4
2019-01-29    4
2019-04-11    4
2017-11-18    4
2019-05-25    4
2019-04-10    4
2018-12-10    4
2018-11-30    4
2018-12-27    4
2018-07-06    4
2016-03-13    4
2016-06-30    4
2016-10-20    4
2016-05-17    4
2016-04-06    4
2017-09-22    4
2019-02-18    4
2019-08-11    4
2017-01-05    4
2016-12-25    4
2019-10-28    4
2018-12-30    4
2017-04-13    4
2016-02-03    4
2017-06-27    4
2018-07-19    4
2018-03-19    4
2017-08-10    4
2018-07-27    4
2017-12-11    4
2018-05-29    4
2017-04-20    4
2018-05-07    4
2018-03-31    4
2016-10-26    4
2019-06-10    4
2018-04-02    4
2019-04-12    4
2016-03-28    4
2016-10-22    4
2019-02-11    4
2017-08-26    4
2018-04-29    4
2017-07-19    4
2018-09-11    4
2016-05-14    4
2018-06-28    4
2018-01-28    4
2017-12-29    4
2016-03-15    4
2019-08-22    4
2017-04-07    4
2018-06-12    4
2017-11-11    4
2017-12-22    4
2019-04-17    4
2018-05-10    4
2018-12-15    4
2016-01-14    4
2016-05-03    4
2015-12-24    4
2016-05-10    4
2018-02-01    4
2017-01-11    4
2017-12-21    4
2016-11-17    4
2018-06-05    4
2019-01-24    4
2016-08-01    4
2017-11-26    4
2016-01-03    4
2016-07-13    4
2018-08-07    4
2019-07-02    4
2017-09-01    4
2018-12-14    4
2018-01-23    4
2019-01-08    4
2019-08-05    4
2017-03-14    4
2017-02-20    4
2019-08-12    4
2019-06-17    4
2018-11-07    4
2017-12-27    4
2016-02-28    4
2016-04-01    4
2018-07-25    4
2017-04-24    4
2017-05-07    4
2017-08-27    4
2017-03-21    4
2016-08-17    4
2016-10-23    4
2019-02-14    4
2016-08-30    4
2016-06-20    4
2016-05-07    4
2017-06-19    4
2019-09-08    4
2016-06-17    4
2016-01-16    4
2019-02-22    4
2018-11-10    4
2019-06-26    4
2017-02-13    4
2019-08-27    4
2019-05-23    4
2017-05-24    4
2019-07-03    4
2016-01-28    4
2017-11-17    4
2016-09-05    4
2016-05-02    4
2019-10-31    4
2016-11-06    4
2017-11-23    4
2016-08-18    4
2018-07-07    4
2017-11-04    4
2018-01-20    4
2016-12-28    4
2018-03-28    4
2016-07-06    4
2017-04-12    4
2018-12-26    4
2019-05-20    4
2018-12-09    4
2018-11-06    4
2018-11-11    4
2018-09-14    4
2019-05-19    4
2017-12-19    4
2017-05-08    4
2016-07-12    4
2017-01-12    4
2018-09-18    4
2018-03-22    4
2017-05-21    4
2019-09-10    4
2017-07-22    4
2016-07-09    4
2018-07-30    4
2018-10-20    4
2019-01-13    4
2016-01-22    4
2018-05-06    4
2018-12-29    4
2018-02-23    4
2018-02-28    4
2016-11-26    4
2016-06-07    4
2019-06-11    4
2016-08-19    4
2016-06-04    4
2019-03-21    4
2019-04-14    4
2019-05-29    4
2018-04-05    4
2018-07-01    4
2018-04-19    4
2017-02-25    4
2019-08-06    4
2019-07-23    4
2017-05-31    4
2019-10-22    4
2017-02-23    4
2018-05-12    4
2018-12-20    4
2019-06-06    4
2019-06-05    4
2018-03-21    4
2018-08-24    4
2018-02-24    4
2019-05-16    4
2017-05-10    4
2019-06-28    4
2019-08-25    4
2018-07-09    4
2018-03-29    4
2017-01-17    4
2018-12-31    4
2018-01-21    4
2018-01-30    4
2019-05-21    4
2018-12-13    4
2019-08-09    4
2018-11-26    4
2016-01-01    4
2017-08-30    4
2016-06-14    4
2018-03-17    4
2015-12-18    4
2019-07-31    4
2018-11-01    4
2018-12-24    4
2019-02-21    4
2019-07-18    4
2018-06-26    4
2018-07-31    4
2019-01-14    4
2018-02-26    4
2017-09-15    4
2019-03-11    4
2017-11-19    4
2018-10-22    4
2016-04-04    4
2017-04-14    4
2018-12-07    4
2019-01-25    4
2019-02-13    4
2019-06-15    4
2016-05-01    4
2017-12-28    4
2018-05-30    4
2017-05-09    4
2016-12-15    4
2019-06-19    4
2018-02-12    4
2019-08-07    4
2017-07-10    4
2019-06-09    4
2017-05-28    4
2016-12-31    4
2016-12-02    4
2017-09-27    4
2018-11-05    4
2018-05-04    4
2018-04-15    4
2018-04-14    4
2018-04-17    4
2017-09-17    4
2019-07-29    4
2016-04-12    4
2019-04-01    4
2018-11-25    4
2018-05-22    4
2016-11-20    4
2017-03-02    4
2018-06-18    4
2018-06-09    4
2018-09-07    4
2017-11-20    4
2017-04-11    4
2017-11-08    4
2016-07-14    4
2017-03-26    4
2019-05-22    4
2018-12-02    4
2018-04-23    4
2019-03-19    4
2019-01-09    4
2017-01-03    4
2017-03-20    4
2018-07-23    4
2017-05-18    4
2017-11-02    4
2018-08-19    4
2017-05-26    4
2017-04-18    4
2017-09-16    4
2019-05-28    4
2018-07-08    4
2017-04-01    4
2019-08-15    4
2015-12-16    4
2017-07-12    4
2016-05-11    4
2018-03-24    4
2017-05-23    4
2018-09-04    4
2017-11-21    4
2017-12-01    4
2016-07-23    4
2017-12-14    4
2018-09-15    4
2016-04-11    4
2016-10-16    4
2019-03-10    4
2018-05-11    4
2019-01-21    4
2017-11-05    4
2018-05-02    4
2019-01-27    4
2018-11-08    4
2019-02-19    4
2018-05-15    4
2018-01-26    4
2019-04-13    4
2016-04-28    4
2017-11-10    4
2019-02-28    4
2016-10-27    4
2017-03-15    4
2016-09-25    4
2017-09-08    4
2017-05-16    4
2019-05-15    4
2017-05-14    4
2017-09-06    4
2018-11-16    4
2016-09-08    4
2018-07-24    4
2018-08-25    4
2016-01-26    4
2017-08-18    4
2018-06-29    4
2018-07-04    4
2018-07-20    4
2016-10-28    4
2018-10-18    4
2018-08-17    4
2017-12-31    4
2016-06-10    4
2018-01-25    4
2019-08-26    4
2019-07-05    4
2017-04-08    4
2018-04-06    4
2017-12-08    4
2016-07-24    4
2017-09-04    4
2016-03-25    4
2018-06-04    4
2019-06-07    4
2019-04-03    4
2017-09-21    4
2018-05-08    4
2018-08-16    4
2019-01-03    4
2019-03-09    4
2018-03-20    4
2019-02-20    4
2018-11-21    4
2019-08-29    4
2016-08-03    4
2016-11-23    4
2017-06-14    4
2018-06-27    4
2019-05-08    4
2016-01-15    4
2019-01-23    4
2017-12-25    4
2016-07-15    4
2019-01-11    4
2018-11-23    4
2019-04-15    4
2016-01-25    4
2019-03-28    4
2018-10-26    4
2017-04-10    4
2016-03-19    4
2018-08-09    4
2015-12-25    4
2016-06-05    4
2016-12-19    4
2016-06-28    4
2018-04-09    4
2019-08-28    4
2019-08-01    4
2016-12-29    4
2016-05-13    4
2016-03-31    4
2016-12-22    4
2016-02-11    4
2017-06-26    4
2017-09-07    4
2018-07-03    4
2016-06-23    4
2018-05-23    4
2016-08-10    4
2019-09-06    4
2016-07-05    4
2016-07-04    4
2016-06-09    4
2018-06-01    4
2016-04-22    4
2019-04-18    4
2016-11-16    4
2017-11-24    4
2017-05-27    4
2018-08-15    4
2018-07-26    4
2018-11-17    4
2017-08-28    4
2018-02-04    4
2017-06-15    4
2019-09-05    4
2016-11-18    4
2019-06-13    4
2017-12-26    4
2016-11-24    4
2016-03-17    4
2018-12-22    4
2018-04-30    4
2016-12-20    4
2019-05-17    4
2018-01-22    4
2016-11-03    4
2018-08-28    4
2017-07-23    4
2016-06-08    4
2016-12-26    4
2016-01-23    4
2017-08-23    4
2018-11-13    4
2017-03-30    4
2017-03-29    4
2016-03-30    4
2019-01-01    4
2019-08-13    4
2016-04-27    4
2019-09-04    4
2019-07-01    4
2019-08-31    4
2019-03-24    4
2019-05-26    4
2016-07-17    4
2019-01-04    4
2016-01-21    4
2016-10-30    4
2016-06-02    4
2018-04-10    4
2017-07-30    4
2017-12-04    4
2016-03-24    4
2018-06-07    4
2017-07-24    4
2017-02-15    4
2016-09-04    4
2019-03-08    4
2017-11-07    4
2018-07-22    4
2018-05-16    4
2018-12-28    4
2018-01-17    4
2017-05-03    4
2018-08-18    4
2018-06-03    4
2016-07-26    4
2017-01-23    4
2018-04-12    4
2018-06-13    4
2019-08-17    4
2018-05-03    4
2019-04-16    4
2019-10-18    4
2018-09-19    4
2016-09-24    4
2017-04-17    4
2019-03-12    4
2018-11-14    4
2018-09-17    4
2016-12-12    4
2018-08-27    4
2018-05-24    4
2018-08-31    4
2017-02-08    4
2019-08-20    4
2018-08-30    4
2018-07-11    4
2017-01-19    4
2017-06-16    4
2017-05-25    4
2018-01-16    4
2017-05-04    4
2017-12-16    4
2017-12-20    4
2018-06-25    4
2019-02-24    4
2017-11-13    4
2017-06-18    4
2017-12-30    4
2016-03-27    4
2017-06-20    4
2019-06-30    4
2019-06-25    4
2017-04-25    4
2017-08-16    4
2016-01-27    4
2018-10-24    4
2017-07-20    4
2017-02-21    4
2018-04-18    4
2019-07-17    4
2017-11-30    4
2016-11-04    4
2019-02-12    4
2017-03-06    4
2016-08-02    4
2018-11-22    4
2017-09-13    4
2017-11-15    4
2016-10-21    4
2017-12-12    4
2019-05-13    4
2017-12-17    4
2016-01-19    4
2018-06-08    4
2019-09-11    4
2016-02-04    4
2018-05-21    4
2016-11-19    4
2019-04-07    4
2016-09-21    4
2018-12-04    4
2017-09-05    4
2017-08-31    4
2019-10-30    4
2018-09-05    4
2016-06-21    4
2016-02-13    4
2019-05-09    4
2019-05-07    4
2018-12-16    4
2018-02-11    4
2016-04-07    4
2016-04-02    4
2018-11-19    4
2018-02-19    4
2017-09-25    4
2018-05-31    4
2019-01-12    4
2017-10-04    4
2018-01-31    4
2017-11-29    4
2019-03-18    4
2019-06-29    4
2019-01-22    4
2017-06-12    4
2016-08-21    4
2019-07-21    4
2019-10-21    4
2017-08-22    4
2019-06-04    4
2017-08-24    4
2018-08-14    4
2016-05-12    4
2017-01-24    4
2016-09-23    4
2016-01-17    4
2019-05-14    4
2017-03-28    4
2019-08-18    4
2017-02-24    4
2018-09-10    4
2018-05-05    4
2017-01-18    4
2019-08-21    4
2019-08-30    4
2016-10-24    4
2016-05-09    4
2019-02-01    4
2018-10-31    4
2017-01-16    4
2017-06-04    4
2017-05-22    4
2019-10-16    4
2016-11-07    4
2016-09-11    4
2019-04-06    4
2017-11-27    4
2019-10-20    4
2016-11-08    4
2019-06-18    4
2019-08-23    4
2018-02-14    4
2016-09-22    4
2017-07-11    4
2019-08-03    4
2016-11-25    4
2019-04-23    4
2018-06-19    4
2017-07-21    4
2017-08-29    4
2016-08-22    4
2016-09-19    4
2018-07-16    4
2018-07-05    4
2019-01-06    4
2017-03-25    4
2019-03-26    4
2017-08-25    4
2018-07-17    4
2016-12-06    4
2018-05-27    4
2016-07-18    4
2016-12-27    4
2017-03-03    4
2017-09-30    4
2019-04-09    4
2018-03-30    4
2017-07-25    4
2019-01-17    4
2017-11-25    4
2016-09-01    4
2018-05-14    4
2016-10-29    4
2018-08-26    4
2019-06-14    4
2018-02-20    4
2017-11-03    4
2018-11-09    4
2019-06-27    4
2017-08-07    4
2016-01-24    4
2016-04-08    4
2018-06-10    4
2017-09-10    4
2016-06-12    4
2018-05-09    4
2019-04-30    4
2016-06-22    4
2019-07-09    4
2017-11-12    4
2017-04-05    4
2018-03-27    4
2019-07-22    4
2016-10-25    4
2017-05-02    4
2018-12-17    4
2018-06-20    4
2018-09-08    4
2018-02-22    4
2016-05-06    4
2018-07-02    4
2016-08-11    4
2016-01-18    4
2016-04-21    4
2017-05-05    4
2019-01-20    4
2018-10-21    4
2016-05-15    4
2018-11-02    4
2017-01-25    4
2016-07-19    4
2017-03-31    4
2016-08-20    4
2019-02-23    4
2016-06-03    4
2018-01-15    4
2018-09-12    4
2019-01-18    4
2017-05-30    4
2017-05-17    4
2015-06-26    3
2017-07-17    3
2015-07-08    3
2015-02-12    3
2015-12-02    3
2016-03-01    3
2015-04-04    3
2016-03-02    3
2018-05-20    3
2015-11-16    3
2015-01-24    3
2015-12-03    3
2015-02-22    3
2015-04-18    3
2015-04-24    3
2015-01-25    3
2016-01-08    3
2015-10-20    3
2015-08-22    3
2015-08-27    3
2015-01-16    3
2015-07-11    3
2015-03-14    3
2016-08-06    3
2015-03-16    3
2015-12-01    3
2015-10-23    3
2015-09-20    3
2015-08-08    3
2015-02-20    3
2015-06-20    3
2015-09-09    3
2015-04-06    3
2015-08-26    3
2015-01-29    3
2015-09-14    3
2015-08-07    3
2015-10-29    3
2016-01-07    3
2015-11-24    3
2015-07-27    3
2019-09-17    3
2015-12-26    3
2019-06-08    3
2015-05-06    3
2015-12-29    3
2015-02-23    3
2015-03-13    3
2015-06-27    3
2015-06-02    3
2015-06-16    3
2015-04-29    3
2015-08-14    3
2015-07-04    3
2019-10-27    3
2015-01-03    3
2015-02-06    3
2015-11-22    3
2015-08-25    3
2016-02-22    3
2015-03-07    3
2015-06-18    3
2015-01-28    3

In [34]:
# code = code.loc[code['개관일'] < '2019-10-31']
print(code.shape)
code.sample()

(43, 3)

    영화상영관코드           영화상영관명         개관일
407  011009  롯데시네마 부산본점(백화점)  2001-06-16

In [132]:
df = data

In [134]:
# CGV 송파-4, 영화의전당-1,롯데시네마 독산 
# 
# df = pd.DataFrame()
theater_name = '영화의전당'
for i in range(1, 2):
    try:
        print(i)
        
        df = pd.concat([df, pd.read_html(f'상영내역-{theater_name}-1-{i}.html')[1]])
    
    except ValueError as e:
        print('[Error]', e)

1

In [135]:
print(df.shape)
df.sample()

(6349, 13)

,10회,11회,1회,2회,3회,4회,5회,6회,7회,8회,9회,상영관,상영일자
3439,nan,NaN,NaN,"14:10, 홀리워킹데이(디지털)","16:00, 인디애니박스:셀마의 단백질 커피(디지털), 5,000원","17:40, 사이비(디지털), 5,000원","19:40, 우리들(디지털), 7,000원",NaN,NaN,NaN,nan,인디플러스 영화의 전당,2016-08-10

In [72]:
# data = pd.concat([df, pd.read_html(f'상영내역-{theater_name}-1-1.html')[1]])
# print(data.shape)
# data.sample()
# data['상영일자'].value_counts()
data.to_csv(f'상영내역-{theater_name}-1.csv', index=False)

In [120]:
code.iloc[38:]

    영화상영관코드                영화상영관명         개관일
455  016045            롯데시네마 광주광산  2018-04-19
484  002227  화성시문화재단 모두누림센터 누림아트홀  2017-03-15
513  002189                 양평시네마  1994-10-29
519  002205          롯데시네마 평촌_샤롯데  2012-03-29
523  007056           롯데시네마 마산터미널  2010-12-15

In [121]:
for name in code['영화상영관명'][39:]:

    theater_name = name.strip().replace(' ', '%20').replace('(', '%28').replace(')', '%29')

# theater_name = '이봄씨어터'
# df = pd.concat([df, pd.read_html(f'상영내역-{theater_name}.html')[1]])
    print(theater_name)
    df = pd.read_html(f'상영내역-{theater_name}.html')[1]
    # df = pd.DataFrame()
    for year in range(1, 5):
        try:
            print(year)

            df = pd.concat([df, pd.read_html(f'상영내역-{theater_name}-{year}.html')[1]])

        except ValueError as e:
            print('[Error]', e)

#         try: 
#             if year == 0:
#                 for month in range(12):
#                     print(year,'-', month)

#                     df = pd.concat([df, pd.read_html(f'상영내역-{theater_name}-{year}-{month}.html')[1]])

#         except ValueError as e:
#             print('[Error]', e)
    
    df.to_csv(f'상영내역-{theater_name}.csv', index=False)
    print(f'{theater_name} 저장완료')

화성시문화재단%20모두누림센터%20누림아트홀
1
2
3
4
화성시문화재단%20모두누림센터%20누림아트홀 저장완료
양평시네마
1
2
3
4
양평시네마 저장완료
롯데시네마%20평촌_샤롯데
1
2
3
4
롯데시네마%20평촌_샤롯데 저장완료
롯데시네마%20마산터미널
1
2
3
4
롯데시네마%20마산터미널 저장완료

In [ ]:
#영화의전당 파일 불러와서 1 추가하기
10부터

In [94]:
print(df.shape)
df.sample()

(4340, 21)

,10회,11회,12회,13회,14회,15회,16회,17회,18회,19회,1회,2회,3회,4회,5회,6회,7회,8회,9회,상영관,상영일자
239,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"10:40, 어벤져스: 엔드게임(디지털), 7,000원","14:05, 어벤져스: 엔드게임(디지털), 10,000원","17:30, 어벤져스: 엔드게임(디지털), 10,000원","20:55, 어벤져스: 엔드게임(디지털), 10,000원",NaN,NaN,NaN,NaN,NaN,08관,2019-04-30

In [103]:
df['상영일자'].value_counts()
df['상영관'].unique()

array(['01관', '검색된 데이터가 존재하지 않습니다.'], dtype=object)

In [137]:
df.to_csv(f'상영내역-{theater_name}.csv', index=False)

# 상영내역 데이터 + 상영관정보 데이터 merge
'상영관정보'에서 관별 좌석 수 데이터를 가져와서 '상영내역'에 붙인 후 저장.  
저장된 csv 파일은 'Theaters_merged_files' 폴더에 있음.

In [31]:
code[150:300]
# ['영화상영관명_new'] = code['영화상영관명'].apply(lambda x: x.replace(' ', '_'))

     영화상영관코드              영화상영관명
150     2075              CGV 판교
151    13012              CGV 대전
152     6035            롯데시네마 안동
153     1192             CGV 의정부
154     2006              CGV 수원
155     1216              CGV 하계
156    14013            CGV 울산삼산
157     2010              CGV 오리
158    11046     CINE de CHEF 센텀
159     1154             CGV 왕십리
160     1158             CGV 영등포
161     1245     CINE de CHEF 용산
162     1128    CINE de CHEF 압구정
163     1016              CGV 강변
164     1230              CGV 천호
165     1111             CGV 압구정
166    13033          메가박스 대전중앙로
167     4046            CGV 충북혁신
168     2042          롯데시네마 평택비전
169     7083        메가박스 양산라피에스타
170     2237            CGV 광교상현
171     9053        CGV 광양엘에프스퀘어
172     2247             1939시네마
173     9029             메가박스 순천
174     7079            메가박스 삼천포
175     4044          메가박스 청주충북대
176     1100  메가박스 EOE4(남산자동차극장)
177     1148             아트하우스모모
178     1197                아트나인
179     1231               명보아트홀
180     8016             전주시네마타운
181     8052          롯데시네마 익산모현
182     4038         영동 레인보우 영화관
183    10018          롯데시네마 제주아라
184     5053             인디플러스천안
185     5051          서천군 기벌포영화관
186    11066                인생극장
187     9030           메가박스 목포하당
188     5064           CGV 천안터미널
189    13017             메가박스 대전
190    12006        메가박스 대구(칠성로)
191    11052             메가박스 덕천
192    11051               영화의전당
193     1080                서울극장
194    15057           메가박스 청라지젤
195    16022        메가박스 콜롬버스 하남
196    16021             메가박스 상무
197    11026        메가박스 해운대(장산)
198     2223         메가박스 하남스타필드
199     2172             메가박스 영통
200     1267       메가박스 상암월드컵경기장
201     2102             메가박스 분당
202     7080             메가박스 마산
203     2210             메가박스 백석
204     4045           CGV 청주터미널
205     5027              CGV 천안
206     9061            CGV 순천신대
207    12035            CGV 대구현대
208     4012             메가박스 충주
209    10002             메가박스 제주
210     1125             메가박스 이수
211     2228            메가박스시흥배곧
212     2222         메가박스 일산벨라시타
213     3025             메가박스 속초
214    12015        메가박스 북대구(칠곡)
215    11025           롯데시네마 해운대
216    14001            롯데시네마 울산
217     1071         롯데시네마 브로드웨이
218    12053      롯데시네마 프리미엄 만경관
219     6077            롯데시네마 영주
220     6029    롯데시네마 구미 프라임 1번가
221     2230            롯데시네마 위례
222     2212           롯데시네마 부천역
223     5060              CGV 보령
224     2243        CGV 스타필드시티위례
225     4043            CGV 청주율량
226     5041              CGV 홍성
227     5049              CGV 서산
228     5046              CGV 당진
229    10016            CGV 제주노형
230     8048              CGV 정읍
231     8231              CGV서전주
232     8230              CGV 군산
233     9050            CGV 여수웅천
234     9020              CGV 순천
235     9064          CGV 목포평화광장
236     9054               CGV광양
237    15056             CGV 연수역
238    15039            CGV 인천논현
239    15020             CGV 주안역
240    15049             CGV 남주안
241     1057              CGV 명동
242     1247             CGV 동대문
243     1106              CGV 불광
244     1251            CGV 건대입구
245     1257              CGV 수유
246    11058             CGV 해운대
247    11045            CGV 아시아드
248    11006              CGV 대한
249    11034              CGV 대연
250     7068            CGV 유성온천
251    13029            CGV 유성노은
252    16038            CGV 광주용봉
253    16046            CGV 광주하남
254     6057              CGV 안동
255     6069            CGV 김천율곡
256     7032              CGV 마산
257     7076            CGV 양산물금
258     7077            CGV 김해장유
259     2200            CGV 평택소사
260     2214              CGV 범계
261     2233              CGV 배곧
262     2117             CGV 북수원
263     2011              CGV 야탑
264     2047              CGV 서현
265     2183              CGV 산본
266     2220              CGV 구리
267     2246          롯데시네마 용인역북
268     6006             메가박스 경주
269     2235           메가박스 미사강변
270     2245        메가박스 용인테크노밸리
271    12054          메가박스 대구이시아
272     4042       괴산자연드림파크 괴산극장
273     5057               태안시네마
274     5054              천안낭만극장
275     5055                스타박스
276     5059               명보시네마
277     5047           조이앤시네마 당진
278     5052             당진아트시네마
279     8227          조이앤시네마 전주점
280     8228             조이아트시네마
281     8049         고창문화원 동리시네마
282     9052            고흥 작은영화관
283    15035              영화공간주안
284     1237         에무 시네마 앤 카페
285     1062             서울아트시네마
286     1227                낭만극장
287     1149                필름포럼
288     1240            더숲 아트시네마
289     1248             씨네큐 신도림
290     1242               이봄씨어터
291    16044             광주독립영화관
292     6071            인디플러스 포항
293     6019             안동중앙시네마
294     6076            씨네큐 구미봉곡
295     6073            씨네큐 경주보문
296     7072             씨네아트 리좀
297     3029               시네마브이
298     3202             알펜시아시네마
299     4014             메가박스 오창

In [21]:
# for nm in code['영화상영관명'][150:300]:
for nm in code['영화상영관명']:
    # 안 받아진 파일    160(완료), 192, 215, 233: 235, 290
    print(nm)
# 위에서 지정해준 인덱스 숫자 n과 m을 사용해 code['영화상영관명'][n:m] 으로 변경

    theaNm = nm.strip().replace(' ', '%20').replace('(', '%28').replace(')', '%29')
    theaNm_detail = nm.strip().replace(' ', '_20').replace('(', '_28').replace(')', '_29')
    time = pd.read_html(f'상영내역-{theaNm}.html')[1]
    capacity = pd.read_html(f'상영관정보/상영관정보-{theaNm_detail}.html', encoding='utf-8')[1].T.drop('스크린코드', axis=0).rename(columns={0:'상영관', 1:'좌석수'})
    time.merge(capacity, how='left', on='상영관').to_csv(f'../Theaters_merged_files/{theaNm}.csv', index=False)

이봄씨어터

In [139]:
# 크롤링 에러났던 상영관 데이터 (csv파일로 저장한 것 불러와서) 다시 merge

for nm in code['영화상영관명'][-2:]:
    print(nm)

    theaNm = nm.strip().replace(' ', '%20').replace('(', '%28').replace(')', '%29')
    theaNm_detail = nm.strip().replace(' ', '_20').replace('(', '_28').replace(')', '_29')
    time = pd.read_csv(f'상영내역-{theaNm}.csv')
    capacity = pd.read_html(f'상영관정보/상영관정보-{theaNm_detail}.html', encoding='utf-8')[1].T.drop('스크린코드', axis=0).rename(columns={0:'상영관', 1:'좌석수'})
    time.merge(capacity, how='left', on='상영관').to_csv(f'../Theaters_merged_files/{theaNm}.csv', index=False)

롯데시네마 평촌_샤롯데
롯데시네마 마산터미널

In [22]:
code[150:300]

     영화상영관코드              영화상영관명
150     2075              CGV 판교
151    13012              CGV 대전
152     6035            롯데시네마 안동
153     1192             CGV 의정부
154     2006              CGV 수원
155     1216              CGV 하계
156    14013            CGV 울산삼산
157     2010              CGV 오리
158    11046     CINE de CHEF 센텀
159     1154             CGV 왕십리
160     1158             CGV 영등포
161     1245     CINE de CHEF 용산
162     1128    CINE de CHEF 압구정
163     1016              CGV 강변
164     1230              CGV 천호
165     1111             CGV 압구정
166    13033          메가박스 대전중앙로
167     4046            CGV 충북혁신
168     2042          롯데시네마 평택비전
169     7083        메가박스 양산라피에스타
170     2237            CGV 광교상현
171     9053        CGV 광양엘에프스퀘어
172     2247             1939시네마
173     9029             메가박스 순천
174     7079            메가박스 삼천포
175     4044          메가박스 청주충북대
176     1100  메가박스 EOE4(남산자동차극장)
177     1148             아트하우스모모
178     1197                아트나인
179     1231               명보아트홀
180     8016             전주시네마타운
181     8052          롯데시네마 익산모현
182     4038         영동 레인보우 영화관
183    10018          롯데시네마 제주아라
184     5053             인디플러스천안
185     5051          서천군 기벌포영화관
186    11066                인생극장
187     9030           메가박스 목포하당
188     5064           CGV 천안터미널
189    13017             메가박스 대전
190    12006        메가박스 대구(칠성로)
191    11052             메가박스 덕천
192    11051               영화의전당
193     1080                서울극장
194    15057           메가박스 청라지젤
195    16022        메가박스 콜롬버스 하남
196    16021             메가박스 상무
197    11026        메가박스 해운대(장산)
198     2223         메가박스 하남스타필드
199     2172             메가박스 영통
200     1267       메가박스 상암월드컵경기장
201     2102             메가박스 분당
202     7080             메가박스 마산
203     2210             메가박스 백석
204     4045           CGV 청주터미널
205     5027              CGV 천안
206     9061            CGV 순천신대
207    12035            CGV 대구현대
208     4012             메가박스 충주
209    10002             메가박스 제주
210     1125             메가박스 이수
211     2228            메가박스시흥배곧
212     2222         메가박스 일산벨라시타
213     3025             메가박스 속초
214    12015        메가박스 북대구(칠곡)
215    11025           롯데시네마 해운대
216    14001            롯데시네마 울산
217     1071         롯데시네마 브로드웨이
218    12053      롯데시네마 프리미엄 만경관
219     6077            롯데시네마 영주
220     6029    롯데시네마 구미 프라임 1번가
221     2230            롯데시네마 위례
222     2212           롯데시네마 부천역
223     5060              CGV 보령
224     2243        CGV 스타필드시티위례
225     4043            CGV 청주율량
226     5041              CGV 홍성
227     5049              CGV 서산
228     5046              CGV 당진
229    10016            CGV 제주노형
230     8048              CGV 정읍
231     8231              CGV서전주
232     8230              CGV 군산
233     9050            CGV 여수웅천
234     9020              CGV 순천
235     9064          CGV 목포평화광장
236     9054               CGV광양
237    15056             CGV 연수역
238    15039            CGV 인천논현
239    15020             CGV 주안역
240    15049             CGV 남주안
241     1057              CGV 명동
242     1247             CGV 동대문
243     1106              CGV 불광
244     1251            CGV 건대입구
245     1257              CGV 수유
246    11058             CGV 해운대
247    11045            CGV 아시아드
248    11006              CGV 대한
249    11034              CGV 대연
250     7068            CGV 유성온천
251    13029            CGV 유성노은
252    16038            CGV 광주용봉
253    16046            CGV 광주하남
254     6057              CGV 안동
255     6069            CGV 김천율곡
256     7032              CGV 마산
257     7076            CGV 양산물금
258     7077            CGV 김해장유
259     2200            CGV 평택소사
260     2214              CGV 범계
261     2233              CGV 배곧
262     2117             CGV 북수원
263     2011              CGV 야탑
264     2047              CGV 서현
265     2183              CGV 산본
266     2220              CGV 구리
267     2246          롯데시네마 용인역북
268     6006             메가박스 경주
269     2235           메가박스 미사강변
270     2245        메가박스 용인테크노밸리
271    12054          메가박스 대구이시아
272     4042       괴산자연드림파크 괴산극장
273     5057               태안시네마
274     5054              천안낭만극장
275     5055                스타박스
276     5059               명보시네마
277     5047           조이앤시네마 당진
278     5052             당진아트시네마
279     8227          조이앤시네마 전주점
280     8228             조이아트시네마
281     8049         고창문화원 동리시네마
282     9052            고흥 작은영화관
283    15035              영화공간주안
284     1237         에무 시네마 앤 카페
285     1062             서울아트시네마
286     1227                낭만극장
287     1149                필름포럼
288     1240            더숲 아트시네마
289     1248             씨네큐 신도림
290     1242               이봄씨어터
291    16044             광주독립영화관
292     6071            인디플러스 포항
293     6019             안동중앙시네마
294     6076            씨네큐 구미봉곡
295     6073            씨네큐 경주보문
296     7072             씨네아트 리좀
297     3029               시네마브이
298     3202             알펜시아시네마
299     4014             메가박스 오창

In [13]:
# 오류 파일 확인
# pd.read_html('상영내역-CGV%20영등포.html') # 160
# pd.read_html('상영내역-영화의전당.html') # 192
# pd.read_html('상영내역-롯데시네마%20해운대.html') # 215
# pd.read_html('상영내역-CGV%20여수웅천.html') # 233
# pd.read_html('상영내역-CGV%20순천.html') # 234
# pd.read_html('상영내역-이봄씨어터.html') # 290

ValueError: No tables found

In [48]:
theater.iloc[
#     160
#              192
#              215
#              233: 235
#              290
            ]

광역단체                                    서울시
기초단체                                    강남구
영화상영관코드                                1242
영화상영관명                                이봄씨어터
총 스크린수                                    1
총 좌석수                                    59
필름 상영관수                                   0
2D 상영관수                                   1
3D 상영관수                                   0
4D 상영관수                                   0
IMAX 상영관수                                 0
상설여부                                     상설
특별관운영여부                                 NaN
가입여부                                     가입
전송사업자명                              인터파크(주)
개관일                              2017-01-11
영업상태                                     영업
운영형태                                     직영
주소           서울특별시 강남구 신사동 532-1 번지 대원빌딩 B2
전화번호                          070-8233-4321
홈페이지                                    NaN
Name: 290, dtype: object